### ISSUE TITLE
client.embeddings.create is not an async function

### ISSUE THREAD

**Issue by HarshaSurampudi** [openai/openai-cookbook#1051]
https://github.com/openai/openai-cookbook/blob/c1bd61f944d46e3539b4a136e4273df79b1b7eed/examples/utils/embeddings_utils.py#L59

![image](https://github.com/openai/openai-cookbook/assets/36491599/4d9f98dd-2fd4-47c3-b29f-a7d5eafc12a1)

**Comment by jacksteamdev** [comment]
Just to add a little more context:

The async functions `aget_embedding` and `aget_embeddings` raise a TypeError, implying that `client.embeddings.create` is not an awaitable function.

https://github.com/openai/openai-cookbook/blob/c1bd61f944d46e3539b4a136e4273df79b1b7eed/examples/utils/embeddings_utils.py#L27-L35

https://github.com/openai/openai-cookbook/blob/c1bd61f944d46e3539b4a136e4273df79b1b7eed/examples/utils/embeddings_utils.py#L50-L61

After copying the preceding code into my project, I see this error:

<img width="717" alt="image" src="https://github.com/openai/openai-cookbook/assets/23390212/c5551e11-fc4c-45a7-a75f-ed4cb3b48dc6">

I'm no Python expert, so I'm simply removing it...
