### ISSUE TITLE
TypeError: Missing required arguments; Expected either ('messages' and 'model') or ('messages', 'model' and 'stream') arguments to be given

### ISSUE THREAD

**Issue by sainisanjay** [openai/openai-cookbook#1062]
OpenAI Version == 1.12.0
Python == 3.9.6 
OS == Mac

Trying to run "Multiclass_classification_for_transactions.ipynb" getting below error: 

<img width="1142" alt="Screenshot 2024-02-21 at 1 03 08 AM" src="https://github.com/openai/openai-cookbook/assets/25616511/1000ad19-2ec6-4933-b6d9-b0b6ea62fe24">

**Comment by sarbazvatanatan** [comment]
ata
