### ISSUE TITLE
Website Q&A: 1-D Input vector issue

### ISSUE THREAD

**Issue by kmad** [openai/openai-cookbook#108]
The ```create_context``` function appears to have an issue comparing the embeddings between question and text. Going through the Notebook works up until the ```answer_question``` function execution, where it fails with the below error.

Perhaps this is due to the difference in data types between the embedding result and the question?

```
File ~/dev/ml/openai-cookbook/solutions/web_crawl_Q&A/env/lib/python3.10/site-packages/scipy/spatial/distance.py:611, in correlation(u, v, w, centered)
    578 """
    579 Compute the correlation distance between two 1-D arrays.
    580 
   (...)
    608 
    609 """
    610 u = _validate_vector(u)
--> 611 v = _validate_vector(v)
    612 if w is not None:
    613     w = _validate_weights(w)

File ~/dev/ml/openai-cookbook/solutions/web_crawl_Q&A/env/lib/python3.10/site-packages/scipy/spatial/distance.py:302, in _validate_vector(u, dtype)
    300 if u.ndim == 1:
    301     return u
--> 302 raise ValueError("Input vector should be 1-D.")

ValueError: Input vector should be 1-D
```

**Comment by kmad** [comment]
Disregard - there was a modification made to the creation of embeddings that removed ```eval```; this issue no longer appears.

**Comment by cadal-cw** [comment]
I'm still having this message. Anyone could help me?
