### ISSUE TITLE
[PROBLEM]

### ISSUE THREAD

**Issue by adkiem** [openai/openai-cookbook#1082]
[optional format]

**Identify the file to be fixed**
utils?

**Describe the problem**
I tried to replicate the reproducable-outputs-with-seed-parameter guide: https://cookbook.openai.com/examples/reproducible_outputs_with_the_seed_parameter.

When importing

```import openai
import asyncio
from IPython.display import display, HTML

from utils.embeddings_utils import (
    get_embedding,
    distances_from_embeddings
)
```

I get this error: `ModuleNotFoundError: No module named 'utils'`

I Updated to `openai=1.3.3` but still got the error.

I assume the `utils` library is something imported by `openai`?

Thanks for your help.

**Comment by bhaskar0402** [comment]
Hi [adkiem] (https://github.com/adkiem) this guide [ reproducable-outputs-with-seed-parameter guide:](https://cookbook.openai.com/examples/reproducible_outputs_with_the_seed_parameter.) is working properly utils module is already present in the example folder. All you need is to setup your .env file( for OPENAI_API_KEY ) and environment 

here are some screenshot 
![Screenshot 2024-03-18 at 11 26 32 AM](https://github.com/openai/openai-cookbook/assets/152780010/67b567cd-1185-483b-a4f1-ce1191f00ee3)

![Screenshot 2024-03-18 at 11 26 18 AM](https://github.com/openai/openai-cookbook/assets/152780010/7ea7ab35-8646-4a23-84d1-4188cb05f085)
 
 I request repository maintainers to close this issue. There is no such issue
