### ISSUE TITLE
 Contribute a web wiki

### ISSUE THREAD

**Issue by chenGit1763113879QQ** [openai/openai-cookbook#110]
Contribute a web wiki

    Hello, recently used your repository's knowledge base to make an introduction site [openai-cookbook-wiki](https://boxtrade.github.io/openai-cookbook-wiki/#/) , if you find it useful you can [fork me](https://github.com/boxtrade/openai-cookbook-wiki) and redeploy or [buy a coffee for me](https://boxtrade.github.io/donate/README) ! If you need help, you can leave a message directly under the repository.

But Files of type ipynb cannot be displayed yet, and I will fix it later

**Comment by logankilpatrick** [comment]
This is pretty neat! Thanks for doing so (note some of the links on the main page 404).
