### ISSUE TITLE
issue running openai.File.create

### ISSUE THREAD

**Issue by abdellahiheiballa** [openai/openai-cookbook#111]
```
search_file = openai.File.create(
  file=open("olympics-data/olympics_search.jsonl"),
  purpose='search'
)
```
openai.error.InvalidRequestError: 'search' is not one of ['fine-tune'] - 'purpose'

**Comment by Achyut-Krishna** [comment]
The error message you are encountering is indicating that the purpose argument you are passing to the openai.File.create method is not valid. The purpose argument must be either 'fine-tune' or 'test'.

If you're looking to use the file for searching, it seems like you might have the wrong API. It looks like you're using the OpenAI API, but the purpose argument only applies to the GPT-3 fine-tuning API, which is used to train a language model on specific tasks.

If you're looking to search within a file, you'll need to write some code that reads the file and performs the search. You can start by opening the file with the open function, and then reading its contents line by line, searching for the desired information as you go.

Here's an example in Python that demonstrates how to search for a specific string within a file:


# Open the file
with open("olympics-data/olympics_search.jsonl") as file:
    # Read each line of the file
    for line in file:
        # Check if the desired string is in the line
        if "desired string" in line:
            # If the string is found, print the line
            print(line)

**Comment by logankilpatrick** [comment]
Exactly, the only place you can pass in purpose is for fine tuning. Some API endpoints like: https://platform.openai.com/docs/api-reference/files/list do return the search parameter, but you cannot pass it in.

**Comment by yungookim** [comment]
> Then why was it not stated in their documentations, this is just the same with not having a documentation at all because it's misleading. I have spent weeks going all round that specific line of code with the same error, read their api documentations countless times and even upgraded my account just for this. How disappointing😞

This might help https://github.com/openai/openai-cookbook/tree/main/transition_guides_for_deprecated_API_endpoints
