### ISSUE TITLE
why when I change the answer if it don‘t know, it will return a wrong answer 【Preventing hallucination】

### ISSUE THREAD

**Issue by alisonzhu** [openai/openai-cookbook#112]
<img width="1127" alt="e2d8bc4cb9b0b1055f243e277938dd87" src="https://user-images.githubusercontent.com/9626624/216901354-126f1da7-cc7c-4558-aaeb-571621455c1e.png">

prompt = """Answer the question as truthfully as possible, and if you're unsure of the answer, say "sorry, 我不知啊".

Q: Who won the 2020 Summer Olympics men's high jump?
A:"""

openai.Completion.create(
    prompt=prompt,
    temperature=0,
    max_tokens=300,
    model=COMPLETIONS_MODEL
)["choices"][0]["text"].strip(" \n")

it return 'Marius Lindvik of Norway.'  but it expected to answer 'sorry, 我不知啊'

**Comment by ted-at-openai** [comment]
Unfortunately the models will still sometimes make mistakes, even with the "if you're unsure of the answer, do X" instructions.
