### ISSUE TITLE
[Suggestion] Being able to share a chat read-only and with being able to participate

### ISSUE THREAD

**Issue by bastetfurry** [openai/openai-cookbook#113]
(I hope this is the right place for such suggestions ^^')
As the topic says, it would be cool if one could share a read-only version of a chat without resorting to copy paste or screenshots. And it would rock if one could give a link to friends with which they could participate in a chat with ChatGPT.

**Comment by ted-at-openai** [comment]
Thanks for the suggestions - and we agree. These things take time to build, and we have a lot of competing priorities. But hope to add it one day.
