### ISSUE TITLE
Repeating Instruction Examples

### ISSUE THREAD

**Issue by athn-nik** [openai/openai-cookbook#116]
Is there a way if I want to query a model for a similar question + set of instruction to avoid passing the instruction every time?
eg.
``` python
prompt = ['which categories does this <thing> fall in from the list below?\n - fruit \n -vegetable \n etc.']
response = openai.Completion.create(model="text-davinci-003",
                                            prompt=prompt,
                                            temperature=0.0,
                                            max_tokens=256,
                                            top_p=1,
                                            frequency_penalty=0,
                                            presence_penalty=0
                                            )
```
I want to ask this question for a lot of different `<things>`, and avoid being billed every time for the same words & instructions.

**Comment by ted-at-openai** [comment]
Unfortunately not.

One option is to train a fine-tuned model to do that task, which won't need instructions.

**Comment by gnmarten** [comment]
no, unfortunately not, although chatbots dream about this feature
![repeat_prompt](https://user-images.githubusercontent.com/4067316/219679788-e16ce7b7-981a-459a-8e46-9155901af0f8.png)

this works so well in the ChatGPT frontend ("do the same"), so: any hints as to how one could "train a fine-tuned model to repeat the task without having to clutter the prompt with its repetition"?

**Comment by MuraraAllan** [comment]
@ted-at-openai on the pricing area it says fine-tuned models are even more expensive for usage ( which would not reduce the cost ). 

`Once you fine-tune a model, you’ll be billed only for the tokens you use. Requests sent to fine-tuned models are billed at our [usage rates](https://openai.com/api/pricing/#quotas).`


@athn-nik, you want to categorize (classify) <things>, and what you are looking for is a way to avoid open.generate each repetitive <thing>, or do I understand it wrong?

Try applying a vector dictionary alongside OpenAI embeddings ( Diversity measurement or classification between <thing> and <already_generated_things> are good examples, in the embeddings link, there is an example of a vectors database using Redis )

You can also use Any approach of NLP to compare the distance between prompted <thing> to <already_generated_things>

Disclaimer:
If <thing> is dynamically classified ( it can be a fruit today and a vegetable tomorrow ), you might need to generate each time, or in time frames within a dictionary.

**Comment by ted-at-openai** [comment]
Fine-tuned models are more expensive per token. If they allow you to use fewer tokens, they can be less expensive. It depends.

**Comment by athn-nik** [comment]
@MuraraAllan I want to do the same "task" for lots of samples, aka ask the same question, give the same instruction and examples and "label" a different text. Eg:
Determine if this pose contains the knees.
Yoga pose: yes
kneel pose: yes
Waving pose: [....]
Similar to this task for many different [....]
