### ISSUE TITLE
 code: 400   input contains sensitive words: [test]

### ISSUE THREAD

**Issue by haike-1213** [openai/openai-cookbook#1224]
raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: Error code: 400 - {'error': {'message': 'input contains sensitive words: [test] (request id: 20240523152007160608893pVIxONYS)', 'type': 'new_api_error', 'param': '', 'code': 'sensitive_words_detected'}}

**Comment by xihajun** [comment]
may I ask how did you solve it? @haike-1213
