### ISSUE TITLE
Running Embeddings encoding locally? 

### ISSUE THREAD

**Issue by stephansturges** [openai/openai-cookbook#123]
Is there any plan to enable the deployment of a model locally to compute embeddings on tokenized text? 

I'm currently using "text-embedding-ada-002" via the API and it's fine, but I'm trying to parse indexes with >1M items and building such an index using web requests is a pain on many levels, and I'd love to find a better-performing way to do this in the future.

**Comment by ted-at-openai** [comment]
No plans for a local model. (That would be more complicated to get working than an API call.)

What are the pain points you'd like to see fixed?

**Comment by stephansturges** [comment]
The API call works fine, I'm just tring to get embeddings for a pandas dataframe with ~500K entries and even with paralellization it's going to take about 2 days, assuming no connection trouble (which is a mess to unwind). It would be kind of cool to have a docker image that could be used to calculate embeddings locally, even if it requires a bunch of GPUs... some of us could use it :)

**Comment by stephansturges** [comment]
At the moment I'm testing with subsets of 1000 units, and I regularly hit one of these:
<img width="1385" alt="image" src="https://user-images.githubusercontent.com/20320678/217918377-33b6f517-9eb2-4b7f-9c4d-1a278404afbe.png">
This throws a wrench in the whole process...

**Comment by ted-at-openai** [comment]
I'm sorry, that's annoying. How frequently are you hitting it? Can you do exponential backoff and resume? Will escalate to eng team.

**Comment by stephansturges** [comment]
It doesn't appear to be correlated with the rate at which I'm making requests, rather the general level of saturation of the OpenAI API. I can chunk the dataframe in 10 row increments sequentially and it will still hit a snag, at most I've got it about 40k rows before it craps out. The error is kind of annoying too because it seems to block automatic retries of the web request, I'll catch it next time and post here.

**Comment by stephansturges** [comment]
BTW I'm making a movie recommendation app :)
![image](https://user-images.githubusercontent.com/20320678/217937847-4cd1a239-2452-4311-886d-69bd26173ab5.png)
![image](https://user-images.githubusercontent.com/20320678/217937876-48818abe-19fb-4756-b6e0-47aacfd54a7d.png)

![image](https://user-images.githubusercontent.com/20320678/217937902-ac344028-55b1-4844-8200-613c7f6dab3d.png)

**Comment by ted-at-openai** [comment]
Here's a script I wrote for batch processing embeddings in case it's helpful: https://github.com/openai/openai-cookbook/blob/main/examples/api_request_parallel_processor.py

**Comment by stephansturges** [comment]
thanks Ted that looks great! I'll give it a try. 
I'd still love to do this locally at some point, In would like to be able to have 1000x more data embedded soon 😅

**Comment by stephansturges** [comment]
Seems to be working great. It throws this error on every new start but it's gathering the embeddings ok.

`Traceback (most recent call last):
  File "/Users/stephansturges/GPTs/FlixGPT/api_request_parallel_processor.py", line 302, in call_API
    append_to_jsonl([self.request_json, self.result], save_filepath)
  File "/Users/stephansturges/GPTs/FlixGPT/api_request_parallel_processor.py", line 322, in append_to_jsonl
    json_string = json.dumps(data)
                  ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ClientConnectorError is not JSON serializable`

**Comment by stephansturges** [comment]
Thanks @ted-at-openai this actually worked great, I let it run overnight and got everything I need. 
FYI there is an issue with UTF-8 coded characters messing up the tokenizer at some point. I'm going to file a PR for a quick and dirty fix but it could do with some deeper investigating.

BTW I'd love to talk to someone at OpenAI about deploying the movie recommendation app I've made with this 😉 Any chance you can put me in contact with someone?

<img width="1399" alt="image" src="https://user-images.githubusercontent.com/20320678/218253048-b4b8e72b-3b35-4910-a082-69475495dd76.png">

**Comment by stephansturges** [comment]
close, will append PR

**Comment by stephansturges** [comment]
FYI here is the app @ted-at-openai  
https://gptflix.streamlit.app/

**Comment by ted-at-openai** [comment]
> BTW I'd love to talk to someone at OpenAI about deploying the movie recommendation app I've made with this 😉 Any chance you can put me in contact with someone?

We are pretty swamped these days, unfortunately. What's the ask?
