### ISSUE TITLE
Is there a way to ask questions that do aggregations on the document set?

### ISSUE THREAD

**Issue by jaikarnyu** [openai/openai-cookbook#124]
@ted-at-openai Since the max token length is 2800, we are chunking and embedding the chunks. This process is efficient when we ask questions that can be answered with 2-3 chunks as context. We have a use case where we need to ask aggregation questions like "How many terms are present in this terms and conditions document". 

Is there a technique to implement this with current limitations? Any hypothesis or hacks on how we can solve this usecase are also welcome. Please shed some light on this.

**Comment by ted-at-openai** [comment]
There's no published technique for solving this that I'm aware of.
