### ISSUE TITLE
[PROBLEM] `solution_one_file_retrieval.js` is actually solution_two_preprocessing's code

### ISSUE THREAD

**Issue by mitchellhislop** [openai/openai-cookbook#1265]
**Identify the file to be fixed**
solution_one_file_retrieval.js

**Describe the problem**
The code contained in this file is actually the code for the preprocessing solution (solution_two_preprocessing.js)

**Describe a solution**
Swap out the code in solution_one_file_retrieval.js with the code from the article

**Screenshots**
solution_one getDriveItemContent code from article: 
![CleanShot 2024-06-28 at 13 54 08](https://github.com/openai/openai-cookbook/assets/171281/cb045f26-d795-45e5-973f-d8a9385cfb43)

solution_one getDriveItemContent code from file (checked out 6/28 1:30pm CDT):
![CleanShot 2024-06-28 at 13 55 06](https://github.com/openai/openai-cookbook/assets/171281/9a3cbcda-6e44-4995-ab3b-d4e271b4b7f1)

**Comment by mitchellhislop** [comment]
I'm attaching what I believe is the intended `solution_one_file_retrieval.js`
[solution_one_actual.js.zip](https://github.com/user-attachments/files/16036088/solution_one_actual.js.zip)

**Comment by maxreid-openai** [comment]
Thanks for flagging! Just pushed a fix
