### ISSUE TITLE
module 'openai' has no attribute 'Search'

### ISSUE THREAD

**Issue by justanotherlad** [openai/openai-cookbook#127]
I tried reimplementing existing functionality of Search endpoint using the new snippet in [search_functionality_example.py](https://github.com/openai/openai-cookbook/blob/main/transition_guides_for_deprecated_API_endpoints/search_functionality_example.py), but it gives the following error:
`AttributeError: module 'openai' has no attribute 'Search'`

**Comment by ted-at-openai** [comment]
Search has now been fully deprecated. I'll remove that line - thank you for the heads up.

**Comment by ted-at-openai** [comment]
Removed: https://github.com/openai/openai-cookbook/pull/130

**Comment by justanotherlad** [comment]
With the edit, the code on running gives the following error for my API_KEY: 
```
raise self.handle_error_response(
openai.error.RateLimitError: You exceeded your current quota, please check your plan and billing details.
```

I have never sent a request before. 
Is this a known bug?([Reddit](https://www.reddit.com/r/OpenAI/comments/zpt4vn/you_exceeded_your_current_quota_please_check_your/) seems to suggest so)

**Comment by ted-at-openai** [comment]
How old is your account? This was your account's very first request?

**Comment by justanotherlad** [comment]
@ted-at-openai : Yes! My account was created about a month back, tops. I see many people complaining to face a similar issue with their very first request [here](https://www.reddit.com/r/OpenAI/comments/zpt4vn/you_exceeded_your_current_quota_please_check_your/) !
