### ISSUE TITLE
[PROBLEM] GPT 4o mini unable to process images

### ISSUE THREAD

**Issue by Kp101coder** [openai/openai-cookbook#1295]
**Identify the file to be fixed**
openai-cookbook/blob/main/examples/gpt4o/introduction_to_gpt4o.ipynb

**Describe the problem**
In the cookbook, it is stated that the new 4o mini that the model is able to accept inputs of text and image. However when using the code provided in openai-cookbook/blob/main/examples/gpt4o/introduction_to_gpt4o.ipynb, section Base64 Image Processing, the AI simply returns responses similar to "I am unable to view the image...".

**Additional context**
By changing the model to GPT 4o and nothing else (changing the model="gpt-4o-mini" to model = gpt-4o"), the desired response is achieved. Either there is an issue with GPT 4o mini API, or the cookbook has mistakenly labeled it as being able to support image inputs.

**Comment by wyy511511** [comment]
```

from openai import OpenAI
import base64
def encode_image(image_path):
    with open(image_path, "rb") as image_file:
        return base64.b64encode(image_file.read()).decode("utf-8")

base64_image = encode_image(IMAGE_PATH)
print(base64_image)


client = OpenAI()
response = client.chat.completions.create(
    model=MODEL,
    messages=[
        {"role": "user", "content": [
            {"type": "text", "text": "describe the image"},
            {"type": "image_url", "image_url": {
                "url": f"data:image/png;base64,{base64_image}"
                # "url": "https://upload.wikimedia.org/wikipedia/commons/e/e2/The_Algebra_of_Mohammed_Ben_Musa_-_page_82b.png"
                }
            }
        ]}
    ],
    temperature=0.0,
)

print(response.choices[0].message.content)
```


This works for me 
<img width="928" alt="image" src="https://github.com/user-attachments/assets/3ac4c693-7f48-4f10-86f6-072b3b51558b">



`pip show openai`

Name: openai
Version: 1.37.0

**Comment by Kp101coder** [comment]
Ah interesting, when I use a picture from my computer, it does not work. But it will work if I use gpt-4o.

**Comment by wyy511511** [comment]
> Ah interesting, when I use a picture from my computer, it does not work. But it will work if I use gpt-4o.

Both base64 and url works for both 4o and 4o-mini  model. You should make more attempts
I do commented the url. The image content is totally different.

**Comment by Kp101coder** [comment]
I see, thank you for letting me know. I will start testing and let you know if it works. Then I'll go ahead and close this too.
