### ISSUE TITLE
Search deprecated

### ISSUE THREAD

**Issue by sathvik2612** [openai/openai-cookbook#13]
InvalidRequestError:  You do not have access to the search endpoint, likely because it is deprecated.

In the second notebook. Thanks in advance

This is a blog I have found.
https://community.openai.com/t/answers-classification-search-endpoint-deprecation/18532

**Comment by ted-at-openai** [comment]
What's the second notebook?

**Comment by sathvik2612** [comment]
olympics-2-create-qa

here is the notebook executed by me
https://github.com/sathvik2612/gpt3-olympics-question-answering/blob/master/Copy_of_olympics_2_create_qa.ipynb

**Comment by ted-at-openai** [comment]
Thanks for highlighting and apologies for my late reply.

For asking questions of a corpus of documents, we recommend this example as the way to get highest quality results: https://github.com/openai/openai-cookbook/blob/main/examples/Question_answering_using_embeddings.ipynb

I've deleted the old Olympic Q&A example from the repo, given that's it no longer the recommended approach and given that it uses the deprecated Search endpoint.

https://github.com/openai/openai-cookbook/commit/563f8db035a843baae0852c43e76fb2d1a981593

Let me know if you need anything else. Will close this issue.
