### ISSUE TITLE
[SUPPORT]Outlook API

### ISSUE THREAD

**Issue by muestrom** [openai/openai-cookbook#1340]
I tried the outlook API and did everything as shown on your web page, I think. When I use the API, I can login and a green message appears "your account is now connected". So it seems I did everything right. However, this repeats every time I access the API, and the actual task is never done. It seems like it gets an invalid token, and therefore tries to connect again and again, ad infinitum. What can be wrong?

**Comment by neehhaa06** [comment]
Hello @muestrom 

fix: #1340
```
I think you have to ensure your app handles token expiration and refreshes tokens correctly. Verify that tokens are stored and sent properly, and check for specific API error messages to diagnose the issue.
```
