### ISSUE TITLE
Trying the File Q&A

### ISSUE THREAD

**Issue by kutaibah** [openai/openai-cookbook#135]
I keep getting Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
After uploading a file 
I tried both local and on vercel

**Comment by seanbetts** [comment]
I am getting the same error - did you resolve this?

**Comment by xuhaoteoh** [comment]
Same here. This was my error:
![MicrosoftTeams-image (7)](https://user-images.githubusercontent.com/56465408/220263926-99b85dbf-4e18-44c1-9bc2-8eb614121a6a.png)

**Comment by xuhaoteoh** [comment]
This was the errors:

`Warning: TT: undefined function: 32
Error:  Error: self-signed certificate in certificate chain
    at TLSSocket.onConnectSecure (node:_tls_wrap:1540:34)
    at TLSSocket.emit (node:events:513:28)
    at TLSSocket._finishInit (node:_tls_wrap:959:8)
    at ssl.onhandshakedone (node:_tls_wrap:743:12) {
  code: 'SELF_SIGNED_CERT_IN_CHAIN',
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [Function: httpAdapter],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      'User-Agent': 'OpenAI/NodeJS/3.1.0',
      Authorization: 'Bearer sk-',
      'Content-Length': 6860
    },
    method: 'post',
    data: `{"model":"text-embedding-ada-002","input":["..."]}`,
    url: 'https://api.openai.com/v1/embeddings'
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false,
      closeEmitted: false,
      [Symbol(kOnFinished)]: []
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError],
      socket: [Function: handleRequestSocket]
    },
    _eventsCount: 3,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: 10485760,
      protocol: 'https:',
      path: '/v1/embeddings',
      method: 'POST',
      headers: [Object],
      agent: undefined,
      agents: [Object],
      auth: undefined,
      hostname: 'api.openai.com',
      port: null,
      nativeProtocols: [Object],
      pathname: '/v1/embeddings'
    },
    _ended: false,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 6860,
    _requestBodyBuffers: [ [Object] ],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: 6860,
      _hasBody: true,
      _trailer: '',
      finished: false,
      _headerSent: true,
      _closed: false,
      socket: [TLSSocket],
      _header: 'POST /v1/embeddings HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/json\r\n' +
        'User-Agent: OpenAI/NodeJS/3.1.0\r\n' +
        'Authorization: Bearer sk-\r\n' +
        'Content-Length: 6860\r\n' +
        'Host: api.openai.com\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/v1/embeddings',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'api.openai.com',
      protocol: 'https:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kEndCalled)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kUniqueHeaders)]: null
    },
    _currentUrl: 'https://api.openai.com/v1/embeddings',
    [Symbol(kCapture)]: false
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON]
}
wait  - compiling /api/search-file-chunks (client and server)...
event - compiled successfully in 218 ms (61 modules)
Error: self-signed certificate in certificate chain
    at TLSSocket.onConnectSecure (node:_tls_wrap:1540:34)
    at TLSSocket.emit (node:events:513:28)
    at TLSSocket._finishInit (node:_tls_wrap:959:8)
    at ssl.onhandshakedone (node:_tls_wrap:743:12) {
  code: 'SELF_SIGNED_CERT_IN_CHAIN',
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [Function: httpAdapter],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      'User-Agent': 'OpenAI/NodeJS/3.1.0',
      Authorization: 'Bearer sk-',
      'Content-Length': 88
    },
    method: 'post',
    data: '{"model":"text-embedding-ada-002","input":"What are the minimum disclosure agreements?"}',
    url: 'https://api.openai.com/v1/embeddings'
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false,
      closeEmitted: false,
      [Symbol(kOnFinished)]: []
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError],
      socket: [Function: handleRequestSocket]
    },
    _eventsCount: 3,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: 10485760,
      protocol: 'https:',
      path: '/v1/embeddings',
      method: 'POST',
      headers: [Object],
      agent: undefined,
      agents: [Object],
      auth: undefined,
      hostname: 'api.openai.com',
      port: null,
      nativeProtocols: [Object],
      pathname: '/v1/embeddings'
    },
    _ended: false,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 88,
    _requestBodyBuffers: [ [Object] ],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: 88,
      _hasBody: true,
      _trailer: '',
      finished: false,
      _headerSent: true,
      _closed: false,
      socket: [TLSSocket],
      _header: 'POST /v1/embeddings HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/json\r\n' +
        'User-Agent: OpenAI/NodeJS/3.1.0\r\n' +
        'Authorization: Bearer sk-\r\n' +
        'Content-Length: 88\r\n' +
        'Host: api.openai.com\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/v1/embeddings',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'api.openai.com',
      protocol: 'https:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kEndCalled)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kUniqueHeaders)]: null
    },
    _currentUrl: 'https://api.openai.com/v1/embeddings',
    [Symbol(kCapture)]: false
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON]
}
wait  - compiling /api/get-answer-from-files (client and server)...
event - compiled successfully in 183 ms (62 modules)

Error: self-signed certificate in certificate chain
    at TLSSocket.onConnectSecure (node:_tls_wrap:1540:34)
    at TLSSocket.emit (node:events:513:28)
    at TLSSocket._finishInit (node:_tls_wrap:959:8)
    at ssl.onhandshakedone (node:_tls_wrap:743:12) {
  code: 'SELF_SIGNED_CERT_IN_CHAIN',
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [Function: httpAdapter],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      'User-Agent': 'OpenAI/NodeJS/3.1.0',
      Authorization: 'Bearer sk-',
      'Content-Length': 1198
    },
    method: 'post',
    responseType: 'stream',
    data: `{"prompt":"Given a question, try to answer it using the content of the file extracts below, and if you cannot answer, or find a relevant file, just output \\"I couldn't find the answer to that question in your files.\\".\\n\\nIf the answer is not contained in the files or if there are no file extracts, respond with \\"I couldn't find the answer to that question in your files.\\" If the question is not actually a question, respond with \\"That's not a valid question.\\"\\n\\nIn the cases where you can find the answer, first give the answer. Then explain how you found the answer from the source or sources, and use the exact filenames of the source files you mention. Do not make up the names of any other files other than those mentioned in the files context. Give the answer in markdown format.Use the following format:\\n\\nQuestion: <question>\\n\\nFiles:\\n<###\\n\\"filename 1\\"\\nfile text>\\n<###\\n\\"filename 2\\"\\nfile text>...\\n\\nAnswer: <answer or \\"I couldn't find the answer to that question in your files\\" or \\"That's not a valid question.\\">\\n\\nQuestion: What are the minimum disclosure agreements?\\n\\nFiles:\\n\\n\\nAnswer:","max_tokens":800,"temperature":0,"model":"text-davinci-003","stream":true}`,
    url: 'https://api.openai.com/v1/completions'
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false,
      closeEmitted: false,
      [Symbol(kOnFinished)]: []
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError],
      socket: [Function: handleRequestSocket]
    },
    _eventsCount: 3,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: 10485760,
      protocol: 'https:',
      path: '/v1/completions',
      method: 'POST',
      headers: [Object],
      agent: undefined,
      agents: [Object],
      auth: undefined,
      hostname: 'api.openai.com',
      port: null,
      nativeProtocols: [Object],
      pathname: '/v1/completions'
    },
    _ended: false,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 1198,
    _requestBodyBuffers: [ [Object] ],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: 1198,
      _hasBody: true,
      _trailer: '',
      finished: false,
      _headerSent: true,
      _closed: false,
      socket: [TLSSocket],
      _header: 'POST /v1/completions HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/json\r\n' +
        'User-Agent: OpenAI/NodeJS/3.1.0\r\n' +
        'Authorization: Bearer sk-\r\n' +
        'Content-Length: 1198\r\n' +
        'Host: api.openai.com\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/v1/completions',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'api.openai.com',
      protocol: 'https:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kEndCalled)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kUniqueHeaders)]: null
    },
    _currentUrl: 'https://api.openai.com/v1/completions',
    [Symbol(kCapture)]: false
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON]
}
error - Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:399:5)
    at ServerResponse.setHeader (node:_http_outgoing:663:11)
    at _res.setHeader (C:\Users\gpteohxh\Desktop\tutorial\openai-cookbook-main\apps\file-q-and-a\nextjs\node_modules\next\dist\server\base-server.js:129:24)
    at sendJson (C:\Users\gpteohxh\Desktop\tutorial\openai-cookbook-main\apps\file-q-and-a\nextjs\node_modules\next\dist\server\api-utils\node.js:195:9)
    at apiRes.json (C:\Users\gpteohxh\Desktop\tutorial\openai-cookbook-main\apps\file-q-and-a\nextjs\node_modules\next\dist\server\api-utils\node.js:351:31)
    at handler (webpack-internal:///(api)/./src/pages/api/get-answer-from-files.ts:52:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.apiResolver (C:\Users\gpteohxh\Desktop\tutorial\openai-cookbook-main\apps\file-q-and-a\nextjs\node_modules\next\dist\server\api-utils\node.js:363:9)
    at async DevServer.runApi (C:\Users\gpteohxh\Desktop\tutorial\openai-cookbook-main\apps\file-q-and-a\nextjs\node_modules\next\dist\server\next-server.js:488:9)
    at async Object.fn (C:\Users\gpteohxh\Desktop\tutorial\openai-cookbook-main\apps\file-q-and-a\nextjs\node_modules\next\dist\server\next-server.js:750:37)
    at async Router.execute (C:\Users\gpteohxh\Desktop\tutorial\openai-cookbook-main\apps\file-q-and-a\nextjs\node_modules\next\dist\server\router.js:253:36)
    at async DevServer.run (C:\Users\gpteohxh\Desktop\tutorial\openai-cookbook-main\apps\file-q-and-a\nextjs\node_modules\next\dist\server\base-server.js:384:29)
    at async DevServer.run (C:\Users\gpteohxh\Desktop\tutorial\openai-cookbook-main\apps\file-q-and-a\nextjs\node_modules\next\dist\server\dev\next-dev-server.js:741:20)
    at async DevServer.handleRequest (C:\Users\gpteohxh\Desktop\tutorial\openai-cookbook-main\apps\file-q-and-a\nextjs\node_modules\next\dist\server\base-server.js:322:20) {
  code: 'ERR_HTTP_HEADERS_SENT',
  page: '/api/get-answer-from-files'
}`

**Comment by robflaherty** [comment]
I was getting this error initially but after restarting the server it went away 🤷‍♂️

**Comment by xuhaoteoh** [comment]
> I was getting this error initially but after restarting the server it went away 🤷‍♂️

How do you restart the server?

**Comment by patriksharma** [comment]
@kutaibah  did you find a solution for this? It was working fine for me in the morning but all of sudden this error start flowing. Any idea or solution you received?

**Comment by patriksharma** [comment]
> Same here. This was my error: ![MicrosoftTeams-image (7)](https://user-images.githubusercontent.com/56465408/220263926-99b85dbf-4e18-44c1-9bc2-8eb614121a6a.png)

Does anyone get any answer of this issue? I'm facing the same and posted issue but no replies yet :

https://github.com/openai/openai-cookbook/issues/159

**Comment by xuhaoteoh** [comment]
Seems like it’s a problem with SSL certification. When I use my personal
laptop instead of my work laptop, the app works fine and there was no
errors.

**Comment by patriksharma** [comment]
@xuhaoteoh  SSL error from openAI side ?
because I have uploaded the same to Vercel and Render for dynamic URL. it loads fine there but throws the same error.
It was working for me day before yesterday and results were really good, All of sudden it stopped working. 

<img width="1436" alt="Screenshot 2023-02-26 at 12 51 00 PM" src="https://user-images.githubusercontent.com/383524/221397707-ccf351fe-c783-4c7c-be97-51fe68673e7a.png">

**Comment by kutaibah** [comment]
I didn't find the solution 
it is not ssl for sure,

**Comment by patriksharma** [comment]
@kutaibah  @ted-at-openai it's working. The reason behind it will be too many requests from same API key. Everything works for me now. 
Just create a new key and make sure you won't upload this key to Github or Gitlab as public repository, as soon as you upload it Your OpenAI API key was determined to have been leaked, which has triggered a key rotation.

If you have one more laptop or pc try same code with new key there it will work.

**Comment by akhil11naseem** [comment]
Having the same issue.
error - Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client

Tried restarting the server and changing the API key. Still no luck.

**Comment by akhil11naseem** [comment]
> Having the same issue. error - Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
> 
> Tried restarting the server and changing the API key. Still no luck.

Following @patriksharma 's advice, creating a new **account** solved the issue. Creating new API key with my first account did not work. Not sure why. Thanks.

**Comment by akhil11naseem** [comment]
Found out the reason why any API key from my first account did not work. Was because it was past the 3 month trial period for that account. Make sure to check your account is still on a plan (whether free or paid). You can check that here: [https://platform.openai.com/account/usage](https://platform.openai.com/account/usage)

**Comment by Cloud-Paris** [comment]
Does anyone have a solution?
![image](https://user-images.githubusercontent.com/72026573/232995807-03150bf0-aee5-4011-812b-89969cadd4b4.png)

**Comment by akhil11naseem** [comment]
@Cloud-Paris see my comments above (https://github.com/openai/openai-cookbook/issues/135#issuecomment-1492961202 and https://github.com/openai/openai-cookbook/issues/135#issuecomment-1496908414). Have you checked if your API key is not expired?

**Comment by natehuman** [comment]
I have figured out that this is due to your free trial period (first 3 months of account opening) running out. You will have to upgrade your membership to get access to the api.
