### ISSUE TITLE
Calculate the embeddings and save them as CSV

### ISSUE THREAD

**Issue by cfelbertp** [openai/openai-cookbook#137]
I am currently following these instructions https://github.com/openai/openai-cookbook/blob/main/examples/Question_answering_using_embeddings.ipynb with my own data. At the point about creating the embeddings it says:

```
document_embeddings = load_embeddings("https://cdn.openai.com/API/examples/data/olympics_sections_document_embeddings.csv")

# ===== OR, uncomment the below line to recaculate the embeddings from scratch. ========

# document_embeddings = compute_doc_embeddings(df)
```

With `document_embeddings = compute_doc_embeddings(df)` I successfully created the embeddings, but unfortunately the instructions don't tell me how to save them as a CSV file to get a file like the Olympics file so I can continue with the tutorial.

Could someone help me with this?

**Comment by ted-at-openai** [comment]
`df.to_csv(filepath)` will save the dataframe as a CSV.

`df = pd.read_csv(filepath)` will load the dataframe from a CSV.

`filepath` is a string.

**Comment by ted-at-openai** [comment]
Ah right, there's some extra formatting that needs to be done to save it in that particular format. Let me look this up. I think it's just one line, maybe two.

**Comment by ted-at-openai** [comment]
(Sorry that the notebook was not written in a more re-usable fashion  - this bit me last year too)

**Comment by ted-at-openai** [comment]
Something like this should work, I think: `pd.DataFrame(document_embeddings).T.to_csv(filepath)`

**Comment by digitaldesaster** [comment]
thx ted, 
this works but the title and heading is missing in the csv file which leads to an error while loading the embeddings. 
as i couldnt figure out how to set the title / heading before creating the csv.. i fixed it by setting the title / heading in the load embeddings function.. 

df = pd.read_csv(fname, header=0)
df = df.set_axis(['title', 'heading'] + list(df.columns[2:]), axis=1)

**Comment by amidonsolutions** [comment]
Thank you @ted-at-openai and @digitaldesaster - your comments above are exactly what I was looking for. Grateful!

**Comment by cfelbertp** [comment]
Many thanks, @ted-at-openai and @digitaldesaster - this helped me a lot!

**Comment by whiteadi** [comment]
Hi, when I save the calculated embeddings with: pd.DataFrame(document_embeddings).T.to_csv(filepath)
I get the file with the index and vectors:
0,0.0031115561723709106,0.00018902790907304734,-0.00190595886670053,-0.029547588899731636,-0.022286130115389824,0.018968993797898293,-0.029436087235808372,-0.0378822386264801,-0.02245337888598442,-0.018146678805351257,0.02940821275115013,-0.020348811522126198,-0.009881717152893543,-0.008892151527106762 ........
but when I load the embeddings from file:

```
def load_embeddings(fname: str) -> dict[tuple[str, str], list[float]]:

    df = pd.read_csv(fname, header=0)
    max_dim = max([int(c) for c in df.columns])
    return {
           (i): [r[str(i)] for i in range(max_dim + 1)] for _, r in df.iterrows()
    }
```

I get: ValueError: invalid literal for int() with base 10: 'Unnamed: 0'

I did try to add after df = pd.read_csv(fname, header=0)

`df = df.set_axis(['column1_name', 'column2_name, column3_name]), axis=1)`

but then I get:
ValueError: invalid literal for int() with base 10: 'Unnamed: 0'

I mean I see the embeddings format in the file it has the vectors so indeed it does not seems ok to me to load it this way but how, sorry I do not know python just try  :)
