### ISSUE TITLE
Rate limit reached for default-global-with-image-limits in organization org-WsxC8le3Zdckh5ECc2IWgJXn on requests per min. Limit: 60.000000 / min. Current: 70.000000 / min. Contact support@openai.com if you continue to have issues. Please add a payment method to your account to increase your rate limit. Visit https://platform.openai.com/account/billing to add a payment method.

### ISSUE THREAD

**Issue by 888yyh** [openai/openai-cookbook#141]
Rate limit reached for default-global-with-image-limits in organization org-WsxC8le3Zdckh5ECc2IWgJXn on requests per min. Limit: 60.000000 / min. Current: 70.000000 / min. Contact support@openai.com if you continue to have issues. Please add a payment method to your account to increase your rate limit. Visit https://platform.openai.com/account/billing to add a payment method.

i met the uppon bug when running the web-qa.py?
please tell me how to solve this?hope you could reply as soon as possible

**Comment by meatinggroup** [comment]
I have exact same issue. and I can't find documentation for python module openai.embeddings. have been stuck for days.

**Comment by logankilpatrick** [comment]
Hey folks, the "Rate limit reached" error is not a bug, it sounds like you are trying to embed a large number of files which is triggering your rate limit, I suggest reading our rate limit guide which goes over the limits and how to work within them: https://platform.openai.com/docs/guides/rate-limits

**Comment by 888yyh** [comment]
> Hey folks, the "Rate limit reached" error is not a bug, it sounds like you are trying to embed a large number of files which is triggering your rate limit, I suggest reading our rate limit guide which goes over the limits and how to work within them: https://platform.openai.com/docs/guides/rate-limits

all the medthods mentioned in the document didn't work

**Comment by 888yyh** [comment]
> > Hey folks, the "Rate limit reached" error is not a bug, it sounds like you are trying to embed a large number of files which is triggering your rate limit, I suggest reading our rate limit guide which goes over the limits and how to work within them: https://platform.openai.com/docs/guides/rate-limits
> 
> all the medthods mentioned in the document didn't work

it worked!Thanks
