### ISSUE TITLE
nextjs-with-flask-server: Error when asking a question (undefined object evaluating 'props.files.length')

### ISSUE THREAD

**Issue by lh8** [openai/openai-cookbook#142]
Using the File Q&A client, I successfully upload a PDF file (and confirm the vector has arrived in Pinecone)
I then ask a question via the File Q&A client and receive the error in the client…

> Unhandled Runtime Error TypeError: undefined is not an object (evaluating 'props.files.length') 
>  Call Stack <unknown>  
>  FileViewerList@ dispatchEvent  [native code] 
>  performConcurrentWorkOnRoot  [native code]

File: https://robodebt.royalcommission.gov.au/system/files/2023-02/transcript-hearing-day-28-31-january-2023.pdf
Question: Who attended?

**Comment by ted-at-openai** [comment]
FYI @isafulf
