### ISSUE TITLE
nextjs-with-flask-server: Error when asking a question ( TypeError: Cannot read properties of undefined (reading 'toLowerCase'))

### ISSUE THREAD

**Issue by Travis-Barton** [openai/openai-cookbook#143]
Uploaded two txts and asked a simple question and got this.

![Screen Shot 2023-02-17 at 4 15 01 PM](https://user-images.githubusercontent.com/39603097/219819811-63d12b35-6ca2-43b9-9a22-aed898a47ab0.png)

**Comment by mithatcak** [comment]
You are most likely hitting the maximum context length. https://platform.openai.com/docs/models/gpt-3

> This model's maximum context length is 4097 tokens, however you requested 4231 tokens (3231 in your prompt; 1000 for the completion). Please reduce your prompt; or completion length.

**Comment by ted-at-openai** [comment]
FYI @isafulf
