### ISSUE TITLE
export OPENAI_API_KEY="<OPENAI_API_KEY>" is not working

### ISSUE THREAD

**Issue by Muhammad-Ahsan-Rasheed** [openai/openai-cookbook#147]
I'm working on Pycharm, in virtual environment. When I try to setup the API key first I get the error **"export : The term 'export' is not recognized as the name of a cmdlet,"**, after a bit research I came to know that export is for unix for windows we use **set**, I tried set and done. But

When I try to finetune.create I get this error: **"Error: No API key provided. You can set your API key in code using 'openai.api_key = <API-KEY>',"**

Python Version: 3.10
IDE: Pycharm
Environment: Virtual Environment

![image](https://user-images.githubusercontent.com/69692532/220273884-4957499d-df14-47c9-82f5-c93e13efda43.png)

**Comment by SeaDude** [comment]
You'll want to rotate your API Key. Your redaction was not adequate.

**Comment by Muhammad-Ahsan-Rasheed** [comment]
Can you elaborate a bit on reduction? I don't want to rotate API key. When I try fine-tuning I get the error of API key is not provided.

**Comment by SeaDude** [comment]
[Redaction](https://www.wordnik.com/words/redaction). Your API key is showing, on the internet. Anyone can charge requests to your account. You'll want to rotate your key asap.

**Comment by Muhammad-Ahsan-Rasheed** [comment]
@SeaDude Thanks mate, updated.

**Comment by ted-at-openai** [comment]
The issue isn't updating the picture - your edit history is still on the thread. Ensure your key has been rotated so that no one can charge requests to your account: https://platform.openai.com/account/api-keys
