### ISSUE TITLE
Wait too long when fine-tuning in classification example

### ISSUE THREAD

**Issue by asd52303** [openai/openai-cookbook#153]
I just tried the fine-tuning classification example.
I tried to execute this line to train the model, but 2 hours passes, it did not have any replies.
![image](https://user-images.githubusercontent.com/65063633/220591116-96f76eb0-11d1-4cbe-8c76-ea09b2649778.png)
Is it normal to finish this line for so long?

**Comment by cooljoecodes** [comment]
Hello, I am having the same problem.  Did you ever get this fixed and if so, how?
