### ISSUE TITLE
QA using Embeddings: Issues running code

### ISSUE THREAD

**Issue by yannickauff** [openai/openai-cookbook#161]
I've tried running the "Question Answering using Embeddings" [code](https://github.com/openai/openai-cookbook/blob/main/examples/Question_answering_using_embeddings.ipynb).

But in the embedding section (starting at `def get_embedding`) I run into an error that I haven't been able to fix: `TypeError: 'type' object is not subscriptable`.

Any suggestions on how to solve this issue?

**Comment by ted-at-openai** [comment]
Option 1: Use a newer version of Python.

Option 2: Delete the type hints in the function definitions.

The error is coming from the type hints; e.g., "-> List[int]".
