### ISSUE TITLE
How do I keep the Chat session focused on a topic?

### ISSUE THREAD

**Issue by tfk12** [openai/openai-cookbook#167]
I find it on help.openai.com. but it seems to be incomplete.

quite wierd.

The main way to keep the conversation focused on a topic is the system message. You can set this

So How can I make the conversation go on?

**Comment by yunfengsay** [comment]
mark

**Comment by MaslinuPoimal** [comment]
Is it possible to keep the conversation persistent like in the browser window? Or is the API only intended to be used for one-shot queries ATM?

**Comment by logankilpatrick** [comment]
> Is it possible to keep the conversation persistent like in the browser window? Or is the API only intended to be used for one-shot queries ATM?

Only designed for one off messages right now, but you can pass in the previous messages in the request so that the API has context on the conversation.

Closing this for now, but we will keep iterating on the docs here to make things more clear!
