### ISSUE TITLE
Batch input for gpt-3.5-turbo

### ISSUE THREAD

**Issue by Hannibal046** [openai/openai-cookbook#168]
Hi, is it possible to give batched input for `gpt-3.5-turbo` just like `text-davinci-003` as introduced in https://github.com/openai/openai-cookbook/blob/main/examples/How_to_handle_rate_limits.ipynb ?

**Comment by logankilpatrick** [comment]
Batch inputs are not currently supported, but may be in the future!

**Comment by ivorytowerdds** [comment]
Hi, is it supported now?

**Comment by JONGSKY** [comment]
Is batch processing currently possible in CHAT such as GPT-3.5-TURBO, GPT-4, etc.? @logankilpatrick
