### ISSUE TITLE
The calling interface always reports connect ETIMEOUT xxx. xxx. xxx. xx: 443

### ISSUE THREAD

**Issue by Mywbj** [openai/openai-cookbook#171]
![image](https://user-images.githubusercontent.com/67814295/222628090-5c17f588-a40b-424f-a082-8a0da46160df.png)
![image](https://user-images.githubusercontent.com/67814295/222628123-973c1ed8-05cc-4222-89f2-feea69cfa87f.png)
This is the code. Are there any mistakes? Why do you keep reporting this error? Is the server not open?

**Comment by logankilpatrick** [comment]
There was some temporary API instability yesterday, it should be resolved now. Please follow up if you are still having this issue and we can debug further.
