### ISSUE TITLE
how to summary 10000 characters in chinese comments using gpt3 summary function(with 2046 token limitations)?

### ISSUE THREAD

**Issue by planetb113** [openai/openai-cookbook#179]

**Comment by hezuogongying** [comment]
尝试分割为多次，再将多次回复合并，再提交一次

**Comment by ismailntl** [comment]
You might want to try and use something like nltk libraries to further refine your prompt

**Comment by kevinjyh** [comment]
You can refer to the link below.

[YouTube: Recursively summarize text of any length with GPT-3](https://youtu.be/fflkFtIwQXo?list=PLcXzzao8hFPJYNStygAKxBoRS7otZtxY5)

[GitHub: daveshap/RecursiveSummarizer](https://github.com/daveshap/RecursiveSummarizer)

**Comment by simonpfish** [comment]
This is a good topic. We'll work on some content for this.
