### ISSUE TITLE
examples parameter error  text davinci 003

### ISSUE THREAD

**Issue by sathvik2612** [openai/openai-cookbook#181]
InvalidRequestError: Unrecognized request argument supplied: example

'''
code:
response = openai.Completion.create(
  engine="text-davinci-003",
  prompt="Write a catchy slogan for a product.\n",
  examples=[
    {
      "input": "A toothpaste that whitens your teeth and freshens your breath.",
      "output": "Sparkle and shine with every smile."
    },
    {
      "input": "A shampoo that nourishes your hair and prevents dandruff.",
      "output": "Healthy hair starts with Head & Shoulders."
    }
  ],
  max_tokens=10,
  temperature=0.5,
  stop="\n"
)

print(response["choices"][0]["text"])
'''

**Comment by sathvik2612** [comment]
I want to perform few shot prompting suggest me how to proceed

**Comment by simonpfish** [comment]
These kinds of questions are better suited for community.openai.com
