### ISSUE TITLE
Please update api_request_parallel_processor.py to support GPT 3.5 Turbo

### ISSUE THREAD

**Issue by Emasoft** [openai/openai-cookbook#193]
Please update api_request_parallel_processor.py to support GPT 3.5 Turbo model and multiple messages content API.

[api_request_parallel_processor.py](https://github.com/openai/openai-cookbook/blob/66b988407d8d13cad5060a881dc8c892141f2d5c/examples/api_request_parallel_processor.py)

Thanks in advance.

**Comment by Neolistic** [comment]
Thank you, I tried to do it in my own environment and kept running into errors. Seems like the changes needed are pretty widespread.

**Comment by ted-at-openai** [comment]
It's been updated, thanks to a community PR. Let me know if you run into any issues.

**Comment by Fawziya** [comment]
@Emasoft , do you have to have an **example_requests_to_parallel_process.jsonl** that support GPT-35-Turbo? I had a hard time figuring out how to run [api_request_parallel_processor.py](https://github.com/openai/openai-cookbook/blob/66b988407d8d13cad5060a881dc8c892141f2d5c/examples/api_request_parallel_processor.py) example_requests_to_parallel_process.jsonl.

Thanks in advance.
