### ISSUE TITLE
How does this library implement context

### ISSUE THREAD

**Issue by zhang-qilin** [openai/openai-cookbook#197]
I'm using gin as the back end of the web, but I can't seem to implement the context when I call, for example when I ask it "What is a chatGPT?" It answered me, but when I asked it again, "Who invented it?" At this time, it replied to me not related to Chatgpt, but other content I hope someone can answer my question, thank you!

**Comment by logankilpatrick** [comment]
Sounds like you need to include the context of previous messages inside the request you send, otherwise it will not remember what was talked about previously.

**Comment by zhang-qilin** [comment]
Ok, I see. Thank you. Now the conversation is normal and the context is normal.

**Comment by zhang-qilin** [comment]
> Sounds like you need to include the context of previous messages inside the request you send, otherwise it will not remember what was talked about previously.

Ok, I see. Thank you. Now the conversation is normal and the context is normal.
