### ISSUE TITLE
File upload status is failed

### ISSUE THREAD

**Issue by kayousef-zz** [openai/openai-cookbook#20]
Hi

I'm trying to finetune a model, but got stuck at file upload. The file status always becomes failed after upload. I tried everything including the exact same sample [here](https://github.com/openai/openai-cookbook/blob/main/examples/azure/finetuning.ipynb)

When I try to retrieve the status of the uploaded file,
`    train_status = openai.File.retrieve(training_id)["status"]`
it shows the status of the file is "failed". I still can't find ways to get detailed error messaging. Any support would be great.

**Comment by ted-at-openai** [comment]
@sorinsuciu-msft, any thoughts?

**Comment by ted-at-openai** [comment]
Did you ever solve this issue?

Apologies I couldn't help.

**Comment by ted-at-openai** [comment]
The Azure fine-tuning guide has been updated. Let us know if you're still hitting the same problem.

**Comment by troublesprouter** [comment]
I see no upload. The file is 2mb. I've tried PDF and TXT and it doesn't upload:

![image](https://user-images.githubusercontent.com/13382230/224555726-ebb335ef-242a-4e89-8264-6d2bc4e8c952.png)
