### ISSUE TITLE
reduce_long() gives wrong result in Section 1.2 olympics-1-collect-data.ipynb

### ISSUE THREAD

**Issue by justanotherlad** [openai/openai-cookbook#209]
**reduce_long()** in **_Section 1.2_** of [olympics-1-collect-data.ipynb](https://github.com/openai/openai-cookbook/blob/c3b920f123a9c92c30b106462b5d5ecf53a4b3ab/examples/fine-tuned_qa/olympics-1-collect-data.ipynb) gives wrong results.
It should take the sentence up to which max_len of token was not exceeded.

Opened a PR #208 to fix it.

**Comment by ted-at-openai** [comment]
Thank you!
