### ISSUE TITLE
vector database with Redis example code problem

### ISSUE THREAD

**Issue by siml1169** [openai/openai-cookbook#211]
got an error message: redis.exceptions.ResponseError: Property `vector_score` not loaded nor in schema
the local Redis database is up and running.
First I tried my own implementation with my own database, then I received this error. I read a bunch of codes from other projects using OpenAI+Redis, couldn't figure out how are they any different from my own code.
At last I tried just running the example code with Wikipedia data base, but I still got the same error code.
Am I missing something here?

**Comment by siml1169** [comment]
issue resolved:
1. example code is fine. Just create a new/different Redis docker image
2. deeper issue being the embedding vector. the error is caused by vector format when implementing creating chunks out of texts
like this (https://github.com/openai/openai-cookbook/blob/main/examples/Embedding_long_inputs.ipynb)
if average = False for the chunks, you will get number of vector instead of the length of the vector

**Comment by opokualbert** [comment]
I'm not creating chunks out of texts but I get this same error. Is this proposed suggestion the solution?
