### ISSUE TITLE
 POST http://localhost:8080/process_file net::ERR_CONNECTION_REFUSED when i run the File Q&A with flask server

### ISSUE THREAD

**Issue by Ayo-faks** [openai/openai-cookbook#212]
When I run the nextjs flask server version of File Q&A, i get the no response on the browser.
After checking the web console for error i get the following below

error processing file: AxiosError: Network Error
xhr.js?43bf:247 
 POST http://localhost:8080/process_file net::ERR_CONNECTION_REFUSED

I ran the code both on gitpod and codespaces and received the same error.

Can anyone please help figure out the problem. The app without the flask server works perfectly fine.

**Comment by fallbackwjj** [comment]
<img width="763" alt="image" src="https://github.com/openai/openai-cookbook/assets/29295120/f1560f8f-0d39-4d31-8c65-fb44f9a7f346">
