### ISSUE TITLE
The API is unable to render the emojis

### ISSUE THREAD

**Issue by Rishikesh-278** [openai/openai-cookbook#23]
Im using that OpenAI' API for converting the Movie titles to emojis!

![image](https://user-images.githubusercontent.com/63153873/195264736-cf13866d-ecb1-4707-9330-8a2f6db5e8c7.png)

The language is Dart and the framework is flutter! This above Code is the API call. The _"movieController"_ is basically the user Input and the _"setState"_  prints the response on screen! The API works and also gives the output but the Emojis are not rendered properly. 

Suppose I give the User Input as "Star wars" then, the response from API is "ððððð" is like this! This happens to any userInput. The emojis do not get displayed properly!

But on the OpenAI's website. it works properly

Any Solution from anyone is appreciated

**Comment by ted-at-openai** [comment]
Can your code editor display UTF-8 text?

Seems like an issue with the program you're using to look at the results, not an issue with the API.

**Comment by Rishikesh-278** [comment]
> Can your code editor display UTF-8 text?
> 
> Seems like an issue with the program you're using to look at the results, not an issue with the API.

Hi Ted, The problem was solved, The problem was not with the API! The problem was related to Charset Encoding and UTF-8 code.
