### ISSUE TITLE
Ossetic

### ISSUE THREAD

**Issue by SoslanOss** [openai/openai-cookbook#232]
Hi,

Could you provide me with any instructions how "to teach" chatgpt to speak my language? I am an Ossetian, we have less than 500K speakers today, so if we could upload Ossetic texts and get an opportunity to communicate with AI on Ossetic, it would have been huge for our language.

Thank you.

**Comment by ted-at-openai** [comment]
Unfortunately there is no good way to teach it. GPT-4 may do better than GPT-3.5-turbo, but I have not tested.

**Comment by SoslanOss** [comment]
Thank you very much! Could you give me any updates on GPT-4, when it is possible?

**Comment by SoslanOss** [comment]
> 



> Unfortunately there is no good way to teach it. GPT-4 may do better than GPT-3.5-turbo, but I have not tested.

Thank you very much! Could you give me any updates on GPT-4, when it is possible?
