### ISSUE TITLE
Front UI doesn't match up with AI limit

### ISSUE THREAD

**Issue by ghost** [openai/openai-cookbook#248]
When you start the "File Q&A" app (https://github.com/openai/openai-cookbook/tree/main/apps/file-q-and-a/nextjs) in the file upload screen it says:

You can upload 30MB per file and unto 75 file. (see attached)
![Screenshot 2023-03-19 at 10 33 11 am](https://user-images.githubusercontent.com/91181815/226145403-8428fdad-dae5-4f7b-ae41-135affad1908.png)

But the console shows the error of 4MB limit (see attached)
![Screenshot 2023-03-19 at 10 31 48 am](https://user-images.githubusercontent.com/91181815/226145384-ef11a068-fc1e-4f79-b165-b5013e009137.png)

What should be the correct limit? how do I fix this? is it really 75 file is the limit?

**Comment by isafulf** [comment]
https://github.com/openai/openai-cookbook/pull/315
