### ISSUE TITLE
Got error message Must provide an 'engine' when using ChatCompletion ap

### ISSUE THREAD

**Issue by vincilee2** [openai/openai-cookbook#249]
Describe the bug
I followed the instructions from https://github.com/openai/openai-cookbook/blob/main/examples/How_to_format_inputs_to_ChatGPT_models.ipynb
but got an error:
openai.error.InvalidRequestError: Must provide an 'engine' or 'deployment_id' parameter to create a <class 'openai.api_resources.chat_completion.ChatCompletion'>

To Reproduce
using a Azure openai endpoint
execute the following code snippets with your own api_key

# Code snippets
```
import openai
openai.api_type = "azure"
MODEL = "gpt-3.5-turbo"
response = openai.ChatCompletion.create(
    model=MODEL,
    messages=[
        {"role": "system", "content": "You are a helpful assistant."},
        {"role": "user", "content": "Knock knock."},
        {"role": "assistant", "content": "Who's there?"},
        {"role": "user", "content": "Orange."},
    ],
    temperature=0,
)
```
# Env
response
OS
macOS

Python version
Python 3.9.13

Library version
openai-python-0.27.2

**Comment by Rammstein-1994** [comment]
Same problem!

**Comment by germanebr** [comment]
When working with an Azure endpoint, you need to use an engine instead of a model, like this:
response = openai.ChatCompletion.create(
    engine=MODEL,
    messages=[
        {"role": "system", "content": "You are a helpful assistant."},
        {"role": "user", "content": "Knock knock."},
        {"role": "assistant", "content": "Who's there?"},
        {"role": "user", "content": "Orange."},
    ],
    temperature=0,
)
