### ISSUE TITLE
The Api is not responding the emojis.

### ISSUE THREAD

**Issue by Rishikesh-278** [openai/openai-cookbook#25]
Hi team OpenAI, I had a similar problem previously!

The OpenAI's API is not responding to the emojis properly!
Many times I get the Response only if I click the submit 5 or 6 times in my App.

This is the Code 👇, Framework: **_Flutter 3.1,  language: Dart_**

![image](https://user-images.githubusercontent.com/63153873/196153209-f5cdfac7-9097-4abc-9c52-a187a631cbef.png)

for a better understanding of the code. 
The  _**movieController.**_text is the user input and the _**setState()**_ prints the emoji on the physical device screen

Whenever I enter any movie name on the official website of OpenAI playground. I get the response 95% of the time!
But when I run my App A lot of times the response is empty. 
Like this 👇

`**_{id: cmpl-62HS5kfwwFcTieTsZOlO3bVcp7rwy, object: text_completion, created: 1666001761, model: text-davinci-002, choices: [{text: , index: 0, logprobs: null, finish_reason: stop}], usage: {prompt_tokens: 13, total_tokens: 13}}
{cache-control: no-cache, must-revalidate, content-length: 239, content-type: application/json}_**`

👆 The above code snippet is the API's header response. after **_choices_** the **_text_** should be the emoji. But a lot of time it's empty.

My App. 
![image](https://user-images.githubusercontent.com/63153873/196158312-ca825888-4606-441d-8802-e1589010d8d9.png)

suppose if my input is a movie like "Black Widow" the text(emoji) is empty in My App.

Many times I get the Response only if I click the submit 5 or 6 times in my App.

Is this a problem in my code or the API? I'm still a Beginner programmer. Any help is appreciated. 

Thank you!

**Comment by Rishikesh-278** [comment]
@ezzcodeezzlife  Are you saying that in the API's prompt parameter I should give some examples?

**Comment by ezzcodeezzlife** [comment]
yes exactly

**Comment by Rishikesh-278** [comment]
Damn,  @ezzcodeezzlife it's working like butter now! 

I have a Question, How can I make this App accessible to the public through a website?

**Comment by ezzcodeezzlife** [comment]
i dont know flutter but yes you can but wrong place to ask and answer this question. im sure there are tons of recourses online :)
