### ISSUE TITLE
How to deploy nextjs-with-flask-server to Vercel

### ISSUE THREAD

**Issue by troublesprouter** [openai/openai-cookbook#258]
I deployed locally. What changes do I need to make to successfully deploy on Vercel?

I tried simply running `vercel` in the root directory but the deployed URL shows a 404 error. I imagine there are a few config changes needed but I don't know which.

**Comment by troublesprouter** [comment]
Alternatively, what's the best / simplest way to deploy nextjs-with-flask-server online?

**Comment by logankilpatrick** [comment]
Hey, I suggest getting in touch with the Vercel team to talk to them about this!
