### ISSUE TITLE
using openai apikey gpt-3.5-turbo works, but gpt-4 does not, why?

### ISSUE THREAD

**Issue by unicomp23** [openai/openai-cookbook#260]
we have an enterprise plan

**Comment by ted-at-openai** [comment]
Sounds like you are still on the waitlist for GPT-4

**Comment by unicomp23** [comment]
And I can access gpt-4 just fine from the playground.

**Comment by unicomp23** [comment]
If I'm on the waitlist @ted-at-openai why does gpt-4 work for me in the playground?

**Comment by ted-at-openai** [comment]
If you can access it in the Playground, then it sounds like you have access.
