### ISSUE TITLE
Fine-tuned_classification   get ERROR：413 Request Entity Too large.

### ISSUE THREAD

**Issue by zhanfengchen** [openai/openai-cookbook#263]
When I fine-tuning with commend `openai api fine_tunes.create -t 'train.jsonl'  -v 'valid.jsonl' -m ada`
![image](https://user-images.githubusercontent.com/21272170/226779091-5d24d00d-3227-408e-8592-1d91951c25ff.png)

Why? My train file is too big? If so, What is the upper limit?

**Comment by yash0902singh** [comment]
Were you able to find out how to fix it? I am currently getting the same error. 
![image](https://user-images.githubusercontent.com/73191510/230022727-790407c4-a249-44e9-996f-ddcb57da6112.png)
