### ISSUE TITLE
When I use OpenAI through API, in what circumstances will OpenAI actively close the HTTP connection that I initiate?

### ISSUE THREAD

**Issue by Zhanhaoxin** [openai/openai-cookbook#269]
I/O error on POST request for "https://api.openai.com/v1/chat/completions": Unexpected end of file from server; nested ex
ception is java.net.SocketException: Unexpected end of file from server

org.springframework.web.client.ResourceAccessException: I/O error on POST request for "https://api.openai.com/v1/chat/completions": Unexpected end of file from server; nested exception is java.net.SocketException: Unexpected end of file from
 server

**Comment by forestwanglin** [comment]
You can try to use https://github.com/forestwanglin/openai-java SDK if you use Java as client language.

**Comment by inconnu26** [comment]
Hi All, This issue is not close, as it is an exception that arises sometimes (as often as 5-10% for me !) it takes over 30 seconds to get this error, so the response time is sometimes very very long...
