### ISSUE TITLE
How to use ChatGPT API to continue a conversation without clearing the previous API call context

### ISSUE THREAD

**Issue by surendransuri** [openai/openai-cookbook#275]
I'm trying to use the ChatGPT API to continue a conversation with a chatbot. However, I noticed that each API call clears the previous context, making it difficult to maintain the conversation flow. Can someone please help me understand how to use the ChatGPT API to continue a conversation without clearing the previous context? I'm looking for guidance on the API parameters or coding techniques that I can use to preserve the conversation context across multiple API calls. Any examples or code snippets would be greatly appreciated.

Additional information: I have tried passing the context parameter in the API call to preserve the conversation context, but it does not seem to work. I am using the OpenAI Python library to make API calls.

**Comment by FrackinFamous** [comment]
You have to either create embeddings of the chat history and save those in a vector database like pinecone or append the messages to the previous one.  There is currently no way to "save" this info through the API that I know of. 

I think this is what you are looking for and should get you started down the path.  You don't have to use LangChain but it's a good place to start to get the ideas going. Let me know if this helps!

https://python.langchain.com/en/latest/modules/memory/getting_started.html

**Comment by olahsymbo** [comment]
@surendransuri   I made a simple fix for this in my article. It could be helpful. https://betterprogramming.pub/a-simple-technique-for-preventing-conversation-drift-in-llm-based-chatbots-f896756adecb

**Comment by ted-at-openai** [comment]
There's no memory. You have to pass in the chat history in each API call.

**Comment by BA2255** [comment]
So everyone using Open AI APIs is sending the whole chat again, this is then using a lot of resources. What about the website version of Chat GPT, does do that too? Wouldn't there be a way to tag each API, and to run a temporary memory or cache inside the model? Not sure if this is technically possible, but this would save Open AI and the customers significant processing.

**Comment by olahsymbo** [comment]
Check out this article. There is a simple fix that uses a naive session approach to handle this https://betterprogramming.pub/a-simple-technique-for-preventing-conversation-drift-in-llm-based-chatbots-f896756adecb

all you have to do is change the session id and the chat history will be cleared.

**Comment by jadaliha** [comment]
> So everyone using Open AI APIs is sending the whole chat again, this is then using a lot of resources. What about the website version of Chat GPT, does do that too? Wouldn't there be a way to tag each API, and to run a temporary memory or cache inside the model? Not sure if this is technically possible, but this would save Open AI and the customers significant processing.

OpenAI chat webpage is using the parameter "parent_message_id". Unfortunately, I could not properly pass this parameter to the API endpoints. The possibility is there, however, you may not be able to use it from the API endpoint that you and I have access to.

**Comment by dearsina** [comment]
> Check out this article. There is a simple fix that uses a naive session approach to handle this https://betterprogramming.pub/a-simple-technique-for-preventing-conversation-drift-in-llm-based-chatbots-f896756adecb
> 
> all you have to do is change the session id and the chat history will be cleared.

This isn't a novel approach, it's doing what OP is trying to _avoid_ doing, but simply appending the previous conversation to the new request. It's a very expensive approach.

**Comment by olahsymbo** [comment]
@dearsina I’m not sure anywhere in the comment or article mentioned **novel** If it was it would be published in an conference proceedings or journal.

**Comment by MrVibe** [comment]
I want to upvote this feature request. It becomes really expensive to re-share the entire chat and responses.

**Comment by olahsymbo** [comment]
An alternative is to ask the model to summarize the chat so far in a limited number of words and pass that as the "context" for previous chats.

**Comment by Kalmuraee** [comment]
That would help, a temp cache or identify the conversation with user generated chatID

**Comment by echan00** [comment]
did anyone find a solution to this?

**Comment by stcalica** [comment]
Instead of passing in the entire chat history, you want to discuss a topic that it has specific knowledge about in a context of your choice. I'm legitimately asking for my own purposes, but a  better solution is to train it on data around the topic, no?

**Comment by alexzender** [comment]
You need to pass all previous messages via Completion API, and if the text becomes too large to pass everything, you can do an API call to summarize your previous chat history, and so reduce the context

**Comment by jpeg2600** [comment]
Seems like you can now create  assistants and threads to maintain a conversation, you just have to send a thread ID instead of the whole thing to keep things going 

Neat feature. I'm struggling to get a JSON every time but that's another matter.

**Comment by zhuyinheng** [comment]
@zgordan-vv
doc: https://platform.openai.com/docs/assistants/overview
demo: https://github.com/openai/openai-python/blob/main/examples/assistant.py
