### ISSUE TITLE
You exceeded your current quota, please check your plan and billing details.

### ISSUE THREAD

**Issue by pint1022** [openai/openai-cookbook#288]
Hello,
My account is ChatGPT plus account. I got the error message when running a discord bot to access openai api. Do I need sign up a any openai program?

best

**Comment by IreneZhou0129** [comment]
ChatGPT plus and Openai API are two separate accounts.

Did you add a payment method here? https://platform.openai.com/account/billing/overview

**Comment by pint1022** [comment]
got it .
thanks
