### ISSUE TITLE
Clipped answers

### ISSUE THREAD

**Issue by jboverio** [openai/openai-cookbook#293]
Hi, lately I'm getting a lot of clipped answers especially from GPT-4. The model outputs a few paragraphs and stops. How long can an output from GPT-4 be? What is happenning? Is it a recent malfunction? Too many requests (I received this as an answer too, although I don't flood the model, I actually give time to it) ?

**Comment by ted-at-openai** [comment]
ChatGPT? API? Stop tokens? Max tokens? Hard to answer without more info.
