### ISSUE TITLE
Constant problems with PyCharm environment and openai-cookbook

### ISSUE THREAD

**Issue by mbalsam-refind** [openai/openai-cookbook#298]
New to python, but experienced developer. 

Using PyCharm both on Linux and Windows. Using Python 3.10.   Having constant problems with Jupiter Notebooks.   Slow execution, constant missing packages.  Works for a while then stops.   Very fast machine, lots of memory,  SSD.. 

Anyone have any magic?  Willing to ditch PyCharm.  What's better?

**Comment by ted-at-openai** [comment]
Which notebook?

If a package is missing, you'll need to install it.

**Comment by mbalsam-refind** [comment]
Many notebooks.  I don’t think it openai.   But I cant find a pattern yet.  One thing that makes it better is to kill the jupter server when visiting a new notebook.

**Comment by mbalsam-refind** [comment]
One bug I found for windows is: 

Entity_extraction_for_long_documents.ipynb

text = textract.process('data/fia_f1_power_unit_financial_regulations_issue_1_-_2022-08-16.pdf', method='pdfminer').decode('utf-8')

OSError                                   Traceback (most recent call last)
File ~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\textract\parsers\pdf_parser.py:54, in Parser.extract_pdfminer(self, filename, **kwargs)
     53 try:
---> 54     stdout, _ = self.run(['pdf2txt.py', filename])
     55 except OSError:

The file pdf2txt.py is missing.

But this is not related to my problem with jupyter.
