### ISSUE TITLE
DALL-E Api cookbook has old API output "caption" -> "prompt"

### ISSUE THREAD

**Issue by rememberlenny** [openai/openai-cookbook#31]

**Comment by rememberlenny** [comment]
https://github.com/openai/openai-cookbook/blob/main/examples/dalle/Intro%20to%20Generation%20and%20Variations%20with%20DALL-E.ipynb

**Comment by ted-at-openai** [comment]
Thanks, I'll take care of it today.

**Comment by ted-at-openai** [comment]
Fixed! https://github.com/openai/openai-cookbook/pull/33
