### ISSUE TITLE
Sorry, something went wrong!

### ISSUE THREAD

**Issue by yuchenlichuck** [openai/openai-cookbook#318]
<img width="826" alt="image" src="https://user-images.githubusercontent.com/38585175/230377095-5b141604-eccb-44f5-8ee4-f8be5a0cfce6.png">

**Comment by AhmadKhodabaks** [comment]
Issue resides in giving a 500 response in requesting api/search-file-chunks

**Comment by AhmadKhodabaks** [comment]
I am currently experiencing no issues with the application. However, it is important to ensure that you possess an active account with available usage. Neglecting to verify the status of one's trial period may result in unsuccessful attempts to use the demo.
