### ISSUE TITLE
The function keep running and never stop when I run  the olympics-1-collect-data.ipynb.

### ISSUE THREAD

**Issue by minLaoGe** [openai/openai-cookbook#320]
1. It's always keep running and can't stop.  I think that the function  of  'def recursively_find_all_pages(titles, titles_so_far=set()' should limit the page count.  But I am not  python developmenter so I can't fixed it. I hope some kindful guys can fixed it, thanks you

**Comment by ted-at-openai** [comment]
I will fix this for the new Q&A + embeddings guide.

Sorry for the trouble!

**Comment by minLaoGe** [comment]
> lol, thank you so much
