### ISSUE TITLE
Add tiktoken to requirements file in chatbot-kickstarter

### ISSUE THREAD

**Issue by alejandrogomez314** [openai/openai-cookbook#323]
Noticed that `openai-cookbook/apps/chatbot-kickstarter/powering_your_products_with_chatgpt_and_your_data.ipynb` throws an error when I import libraries due to tiktoken not being included in the requirements.txt file of the folder. I suggest adding it there since that solves my problem. I can also create a PR for it.

**Comment by colin-openai** [comment]
Made this change and linked a PR - thanks for raising @alejandrogomez314
