### ISSUE TITLE
InvalidRequestError: The model: `code-davinci-002` does not exist

### ISSUE THREAD

**Issue by spilehchiha** [openai/openai-cookbook#349]
Example [Jupyter notebook](https://github.com/openai/openai-cookbook/blob/main/examples/Unit_test_writing_using_a_multi-step_prompt.ipynb) titled **Unit test writing using a multi-step prompt** utilizes now-deprecated `code-davinci-002` model and running the notebook produces the error.
```
InvalidRequestError: The model: `code-davinci-002` does not exist
```

`code-davinci-002` is mentioned at two locations in the notebook:

First, in the first cell, discussing the multi-step prompt,

```
- Different models for different steps (e.g., `text-davinci-002` for the text planning steps and `code-davinci-002` for the code writing step)
```

and second, as the value for the `code_model` parameter of function `unit_test_from_function`
```
code_model: str = "code-davinci-002",  # if you don't have access to code models, you can use text models here instead
```

A model replacement is suggested.

**Comment by Abhiram-003** [comment]
same issue
Have you found any solution??

**Comment by JusttCallMeMike** [comment]
same

**Comment by ted-at-openai** [comment]
As of last month, there's an updated version: https://github.com/openai/openai-cookbook/blob/main/examples/Unit_test_writing_using_a_multi-step_prompt.ipynb

You can also change the model from `code-davinci-002` to `text-davinci-002`.

**Comment by ted-at-openai** [comment]
Not the same, but should be similar. It's the same base model: https://platform.openai.com/docs/model-index-for-researchers

**Comment by Feng-Jay** [comment]
Hi, I also meet this problem :`The model `code-davinci-002` does not exist or you do not have access to it.`

But I notice there is a [page](https://platform.openai.com/docs/deprecations) mentioned that code-davinci-002 will shut down at 2024. So, we can not use it now?

**Comment by ted-at-openai** [comment]
code-davinci-002 is no longer available to the general public. It's available to researchers only. It will be shut off in 2024. Use the new version of the notebook.
