### ISSUE TITLE
Azure - Question answering using embeddings-based search

### ISSUE THREAD

**Issue by geg00** [openai/openai-cookbook#359]
I'm using python 3.11.3
Windows 

[Question answering using embeddings-based search](https://github.com/openai/openai-cookbook/blob/main/examples/Question_answering_using_embeddings.ipynb)

Looks like the embedding are different for Azure becuase the code 

`def strings_ranked_by_relatedness(

    query: str,

    df: pd.DataFrame,

    relatedness_fn=lambda x, y: 1 - spatial.distance.cosine(x, y),

    top_n: int = 100

) -> tuple[list[str], list[float]]:

    """Returns a list of strings and relatednesses, sorted from most related to least."""

    query_embedding_response = openai.Embedding.create(

        model=EMBEDDING_MODEL,

        deployment_id=EMBEDDING_MODEL,

        input=query,

    )

    query_embedding = query_embedding_response["data"][0]["embedding"]

    strings_and_relatednesses = [

        (row["text"], relatedness_fn(query_embedding, row["embedding"]))

        for i, row in df.iterrows()

    ]

    strings_and_relatednesses.sort(key=lambda x: x[1], reverse=True)

    strings, relatednesses = zip(*strings_and_relatednesses)

    return strings[:top_n], relatednesses[:top_n]

`
I'm using the deployment_id as part of the call. 
Is returning some different answers
Can you confirm?

**Comment by ted-at-openai** [comment]
How different are they? I believe there's some small variability for each request. Not sure if this explains the difference you see.
