### ISSUE TITLE
Documents Embedding Engine vs Query Embedding Engine

### ISSUE THREAD

**Issue by gdeleva** [openai/openai-cookbook#362]
Hello all,

In Semantic_text_search_using_embeddings.ipynb following comment is reported

"Remember to use the documents embedding engine for documents (in this case reviews), and query embedding engine for queries."

Are there two embedding engines? I may be wrong, but by looking at the code I thought that both types are embedded in the same way, usually with text-embedding-ada-002. Can you please tell me if there are different ways to embed text?

Best regards

**Comment by ted-at-openai** [comment]
Whoops, I'll fix that.

There used to be two different engines - one for documents and one for queries - but `text-embedding-ada-002` replaced both.

**Comment by ted-at-openai** [comment]
Fixed in #364
