### ISSUE TITLE
security issues

### ISSUE THREAD

**Issue by jc-rm** [openai/openai-cookbook#363]
Hello!

I can run sudo linux commands in any shell in the ChatGPT-4 servers cluster.

I'd rather not write the details here, but if anyone wants to know how I do it, just email me and I'll give you a full explaining answer of what I'm talking about.

**Comment by ted-at-openai** [comment]
Please report it here: https://openai.com/blog/bug-bounty-program

Thank you!

**Comment by jc-rm** [comment]
Thanks for your answer Ted.

Now I need go to the bed, and I can't write the problem, because it go to take a little bit time to me, but tomorrow I will write where you have said.

Anyway, good night.


_____________________________________









-------- Original Message --------
From: Ted Sanders ***@***.***>
Apparently from: ***@***.***
To: openai/openai-cookbook ***@***.***>
Cc: jc-rm ***@***.***>, Author ***@***.***>
Subject: Re: [openai/openai-cookbook] security issues (Issue #363)
Date: Thu, 20 Apr 2023 21:32:43 -0700
