### ISSUE TITLE
QA: who is loss function is optimal choice? in L2 distance, Cosine Distance and Inner product distance. about text embedding scene.

### ISSUE THREAD

**Issue by daidai21** [openai/openai-cookbook#365]
who is loss function is optimal choice? in L2 distance, Cosine Distance and Inner product distance. about text embedding scene.

[link](https://github.com/openai/openai-cookbook/blob/main/examples/Question_answering_using_embeddings.ipynb)

![image](https://user-images.githubusercontent.com/36124626/233822744-4ae1314f-bb23-4e44-80e2-8db573d79a67.png)

What experiences do you have to share? or Historical experimental data?

tks!

**Comment by ted-at-openai** [comment]
They'll all give the same rankings.
