### ISSUE TITLE
Visualizing_embeddings_in_2D - AttributeError: 'list' object has no attribute 'shape'

### ISSUE THREAD

**Issue by drnic** [openai/openai-cookbook#37]
When I run the `examples/Visualizing_embeddings_in_2D.ipynb` notebook, I get an error during `tsne.fit_transform(matrix)`:

```
    791 def _check_params_vs_input(self, X):
--> 792     if self.perplexity >= X.shape[0]:
    793         raise ValueError("perplexity must be less than n_samples")

AttributeError: 'list' object has no attribute 'shape'
```

Is this a problem with library versions I have installed? A regression from newer versions?

<img width="1129" alt="image" src="https://user-images.githubusercontent.com/108/203911923-e871966e-c2f0-4be7-b48f-e17b7250f10e.png">

<img width="1130" alt="image" src="https://user-images.githubusercontent.com/108/203911585-6eb905bf-f64b-4e7b-8002-a8206f30d173.png">

Sorry if this is a noob python/pandas library mismatch question.

**Comment by fatonhoti** [comment]
On line `[9] matrix = df.babbage_similarity.apply(eval).to_list()` you convert the Series to a Python list whereas the method `fit_transform` from `sklearn.manifold.TSNE` takes in an `ndarray`. You simply need to remove the `to_list()` call and leave it as an ndarray as it originally is.

**Comment by ted-at-openai** [comment]
I tried to reproduce but it works fine for me. I see that your sklearn package says that it's deprecated and to use scikit-learn instead. Suspect that might be your problem.

**Comment by ted-at-openai** [comment]
Try installing scikit-learn and see if that fixes things for you. Thanks for including the helpful screenshots!

**Comment by rastan77** [comment]
I have scikit-learn and it is showing me the same AttributeError.
