### ISSUE TITLE
Special characters not accepted for filenames (Windows)

### ISSUE THREAD

**Issue by sonnyjon** [openai/openai-cookbook#370]
While crawling the OpenAI website, it came upon this URL: https://openai.com/research?topics=language and crashed with the following error In the file web-qa.py on **line 140**:

    with open('text/'+local_domain+'/'+url[8:].replace("/", "_") + ".txt", "w", encoding="UTF-8") as f:
`OSError: [Errno 22] Invalid argument: 'text/openai.com/openai.com_research?topics=language.txt'`

Need to replace the '?' and '=' characters for the text filename that it tries to write to.

**Comment by faizan-maknojia** [comment]
The code is attempting to generate a file named 'openai.com_research?topics=language.txt', which includes both the characters '?' and '='. These characters are typically not permissible in filenames across various operating systems.
Maybe this should work:

```
filename = 'openai.com_research?topics=language.txt'
filename = filename.replace('/', '_').replace('?', '_').replace('=', '_')
with open('text/'+local_domain+'/'+filename, "w", encoding="UTF-8") as f:
```
