### ISSUE TITLE
What are the best parameters for...

### ISSUE THREAD

**Issue by securigy** [openai/openai-cookbook#371]
I need GPT-3.5 API to classify my email, resulting in 2-3 words. What would be the best parameters for gpt-3.5-turbo model for doing this? (I mean: temperature, frequency penalty, etc., etc....)

**Comment by tedsanders** [comment]
What do you think, based on the documentation you've read?

**Comment by securigy** [comment]
Would I be asking, if I knew the answer? No, I would not...

**Comment by OrlyVieraH** [comment]
> I need GPT-3.5 API to classify my email, resulting in 2-3 words. What would be the best parameters for gpt-3.5-turbo model for doing this? (I mean: temperature, frequency penalty, etc., etc....)

answer by GPT-3.5 :
```
As an AI language model, I cannot provide specific parameters for the GPT-3.5 API as it ultimately depends on the specific use case and data being analyzed. However, some general guidelines to consider when fine-tuning the GPT-3.5 model for email classification are:

1. Temperature: Setting a lower temperature will result in more conservative predictions, while a higher temperature will produce more diverse and creative responses. For email classification, it may be best to use a lower temperature to ensure more accurate and consistent classifications.

2. Frequency penalty: This parameter penalizes the model for repeating the same words or phrases too frequently. Setting a higher frequency penalty can help ensure the model produces more varied and informative classifications.

3. Context length: This refers to the number of words or tokens used to generate each prediction. A longer context length may result in more accurate classifications, but may also increase processing time.

4. Training data: The quality and quantity of training data used to fine-tune the model will have a significant impact on its performance. It is important to ensure the training data is diverse and representative of the types of emails you want to classify.

Overall, it is recommended to experiment with different parameter settings and evaluate the model's performance on a validation set to find the optimal configuration for your specific use case.
```

answer by me :)
Firstly, I recommend creating a GOOD instruction with at least the classification tags that you intend to use with GPT. Be as explicit as possible in the tag names to increase the chances of 0 shot. Start with a low temperature (I would start with 0 and even stay there). In my opinion, penalties are not necessary considering you will be making requests one by one, but if you were to do everything in the same 'chat', remember that classifications tend to repeat, so no frequency penalty... Otherwise, the token count is what's lefting (if I'm not mistaken, it counts both request and response together, so you have no choice but to test with the longest email to avoid errors). I would also set top_p to 0 and start testing from there. 
Something easy to digest so you don't have to read too much in the documentation...

**Comment by securigy** [comment]
Thanks, I am quite familiar with parameters and did a lot of experimentation with them. However, I thought somebody specifically tested them for a case of email classification... 
I have a good prompt, I think and a list of categories for GPT-3.5-turbo to choose from, but the API does not get through returning Bad Request (400). For example:

In the regular OpenAI chatbot with GPT-3.5-turbo it works well:
[SYSTEM]
You are experienced email classifier. You take email subject and body text and determine the classification of the email in the form of 2 to 3 words, formatted as {category}-{subcategory}-{subsubcategory} (one word each), where the 'subsubcategory' is optional. Use categories from the given 'Category List'. If the 'Category List' does not include the best matching category, come up with your own category that matches the email context the best.
[USER]
Subject: Learn How to Maximize your FREE RevDriver Account
Body: Spend less time prospecting on LinkedIn with SalesIntel’s RevDriver. Finding direct lines to decision makers is now easy.
 Start Using RevDriver to Generate Leads Today
 If you haven’t already, jump into LinkedIn and start using RevDriver, powered by SalesIntel! It’s a simple way to find the work mobile numbers, email, and other contact information you need to get in touch with decision-makers today. 
 After all, a recent study    showed people are 700% more likely to reach prospects using SalesIntel’s work mobile numbers.
 Generate New Leads   	
 Already a RevDriver Power User? 
 Access 100M verified prospects & premium intent data within the SalesIntel.
 Plans start at just $99 per month!
 Explore Pricing   	
 SalesIntel Research Inc, 1100 North Glebe Rd., Suite 1010, Arlington, VA 22201, USA 
 Unsubscribe    
   
Category List: (this is partial only - for clarity)
Work-Projects
Work-Travel
Work-Team-Communication
Work-Company-Newsletter
Work-Development
Work-Human-Resources
Work-IndustryNews
Work-Training
Work-VendorCommunication
Work-Networking

[assistance]
Work-Subscriptions-Marketing
========

But in API with it does not... My API are well tested and working in other apps. See my other products with them:
https://www.gpt4office.com

I used 4,000 max tokens...

Ideas?

**Comment by securigy** [comment]
You are probably a chatBot itself, and obviously did not understand the problem that I am facing. I already implemented all the "recommendations" that you suggested before I posted the question... and so you will know - I am not looking to automatically to respond to emails as you imply. I am looking to automatically classify emails. It works from chatGPT prompt, both GPT-4 and GPT-3.5-turbo, but is not working using API and GPT-3.5-turbo. Anyway, don't bother to answer with your canned advices...

**Comment by securigy** [comment]
The email content and the prompt that I am sending is way less than 4,000 tokens, which is equivalent to 2 pages of densely populated text. I tested all this with command line ChatGpt and it worked just fine. I also tested this set of parameters in other working applications that I wrote, and the set was valid. That's why I asked if there any special settings required for parameters for email classification... Anyway, I have no choice but to continue experimenting...

**Comment by OrlyVieraH** [comment]
No special set of parameter for some specific action but diferent endpoints (models). If you are using the same model as in your others projects then check carefully the parameters that you are using in this case. I tell you again... if you are using gpt-3.5-turbo 4000 tokens is an invalid parameter:
`This model's maximum context length is 4097 tokens. However, you requested 4736 tokens (736 in the messages, 4000 in the completion). Please reduce the length of the messages or completion.`

**Comment by securigy** [comment]
My understanding of max_tokens was/is that it includes both the prompt and the response.  The response is 3-words long (as instructed in the prompt) so it is negligeable... Are you telling me that my prompt is more 4,097 tokens?

**Comment by OrlyVieraH** [comment]
I edited my last comment...

**Comment by securigy** [comment]
I repeat:  "4000 (is only for completion) is incorrect" - 4,000 is for both prompt and response.
Documentation states:
max_tokens
integer
Optional
Defaults to inf
The maximum number of [tokens](https://platform.openai.com/tokenizer) to generate in the chat completion.

The total length of input tokens and generated tokens is limited by the model's context length.

**Comment by OrlyVieraH** [comment]
Oh well... if you are sure, then you don't need help. You are a perfect coder and reader of documentation. I will try to be like you, so excuse me. I'm going to study, and maybe in two years I'll come back here to give you the reason.
