### ISSUE TITLE
zero-shot_classification_with_embeddings has repeated content

### ISSUE THREAD

**Issue by Jessen-Li** [openai/openai-cookbook#373]
https://github.com/openai/openai-cookbook/blob/main/examples/Zero-shot_classification_with_embeddings.ipynb
step [3] and step [4] are exactly the same,  they all use the same labels, and generates the same results, including the display.

**Comment by ted-at-openai** [comment]
Good call - not sure how that happened. I'll fix it. Thanks for flagging!
