### ISSUE TITLE
Chatbot Kickstarter: Issue following demo

### ISSUE THREAD

**Issue by hossamantarkorin** [openai/openai-cookbook#379]
Hi, I am running the Jupyter notebook locally for the subject app. I am running Pyhton 3.9.16 and have installed and imported all packages necessary. I am having an issue running the Ingestion step where we're initializing the tokenizer and processing the pdf's (the entire error is attached):
 TypeError: expected str, bytes or os.PathLike object, not NoneType
I am confident that the "pdf_path" is not a NoneType
[error_chatbot_kickstarter.txt](https://github.com/openai/openai-cookbook/files/11359630/error_chatbot_kickstarter.txt)

**Comment by Wiiki0807** [comment]
Same here, 
[Enviroment]
Python 3.11
Windows 11
VS code


I checked the variable 'pdf_path' which has assign the .pdf path
<img width="768" alt="image" src="https://github.com/openai/openai-cookbook/assets/27147987/77d73d9d-16e5-48c7-bdb3-ecc5cfb84503">


But when I run  text = textract.process(pdf_path, method='pdfminer')
it have TypeError: expected str, bytes or os.PathLike object, not NoneType
<img width="773" alt="image" src="https://github.com/openai/openai-cookbook/assets/27147987/7499dd8d-dbc2-48f3-8101-eb075b2e43bc">
<img width="762" alt="image" src="https://github.com/openai/openai-cookbook/assets/27147987/09a1837c-e3da-4943-a067-38c3a7706eb8">

**Comment by simonpfish** [comment]
Hello! Thank you for flagging. We'll be giving this demo a revamp soon. Closing this in the meantime.
