### ISSUE TITLE
Chatbot Kickstarter: Issue following demo #379

### ISSUE THREAD

**Issue by hyl3520** [openai/openai-cookbook#389]
Met similar issue as #379 
In Jupyter of VS code on Windows 10 with Python 3.10.9

running the Ingestion step where we're initializing the tokenizer and processing the pdf's (the entire error is attached):
**TypeError: expected str, bytes or os.PathLike object, not NoneType**
full error output:
[error output.txt](https://github.com/openai/openai-cookbook/files/11373668/error.output.txt)

**Comment by foxworld306** [comment]
The same issue here:
TypeError: expected str, bytes or os.PathLike object, not NoneType
Win 11 with Python 3.11.2
