### ISSUE TITLE
Question about using embedding table

### ISSUE THREAD

**Issue by artourl** [openai/openai-cookbook#396]
In my understanding, language models and embedding models are bound together during training. If I use a different embedding model, will the language model still work effectively? Or is it the case that the backend actually maintains different versions of the GPT model that have been fine-tuned with different embedding models, and will route to different GPT versions based on my configuration?
<img width="709" alt="image" src="https://user-images.githubusercontent.com/18308422/236597796-3ac5a9b6-3bac-4b45-8b2d-7f3897432100.png">

**Comment by ted-at-openai** [comment]
You can use any embedding model you like. Doesn't even need to be an OpenAI model.
