### ISSUE TITLE
Feature suggestion for ChatGPT: stop generating response by command typed into text field

### ISSUE THREAD

**Issue by CodingSpiderFox** [openai/openai-cookbook#397]
I don't know where else to put this feature suggestion as I can't find a public repo for the OpenAI ChatGPT Web-frontend

Following situation: 
I was translating some relatively long text with ChatGPT. While ChatGPT was still generating a response, I had the idea to request some change to the generated response. So I wanted to stop generating and provide additional requirements in the text input field.
I prefer using the keyboard a lot. So I didn't want to grab the mouse to click the "Stop generating" button and just tried to type "stop" and press enter in the input field. Unfortunately that did not have any effect.
I would like to have the option to stop generating by typed commands like "stop" or "abort"

**Comment by ted-at-openai** [comment]
Try pressing escape
