### ISSUE TITLE
No such File object: file-c3shd8wqF3vSCKaukW4Jr1TT in notebook fine-tuned_qa

### ISSUE THREAD

**Issue by Bulmenisaurus** [openai/openai-cookbook#41]
I am trying to get the notebooks in the [`fine-tuned_qa`](https://github.com/openai/openai-cookbook/tree/main/examples/fine-tuned_qa). I am experiencing an error with notebook, specifically in the code block with the following code
```python
for name, is_disc in [('discriminator', True), ('qa', False)]:
    for train_test, dt in [('train', train_df), ('test', test_df)]:
        ft = create_fine_tuning_dataset(dt, discriminator=is_disc, n_negative=1, add_related=True)
        ft.to_json(f'{name}_{train_test}.jsonl', orient='records', lines=True)
```
```
No such File object: file-c3shd8wqF3vSCKaukW4Jr1TT
No such File object: file-c3shd8wqF3vSCKaukW4Jr1TT
No such File object: file-c3shd8wqF3vSCKaukW4Jr1TT
...
```
Searching online for this file id didn't return any results, and from my understanding of the [Files documentation](https://beta.openai.com/docs/api-reference/files/list) I'm supposed to upload this file, but I don't know how or where?

**Comment by Bulmenisaurus** [comment]
Alright, this seems to be caused by the fact that even though we do generate correct file id in notebook 2 in section 2.5, it is then overwritten in notebook three. Leaving this issue open because this still needs to be solved, probably by removing the reassignment ```python
olympics_search_fileid = "file-c3shd8wqF3vSCKaukW4Jr1TT"
``` in the very beginning of notebook 3.

**Comment by logankilpatrick** [comment]
I will update this in the next couple of days, thanks for pointing it out!

**Comment by ted-at-openai** [comment]
I'm going to close this because I don't think we're going to get to it, unfortunately. Best wishes.
