### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by khalilmaysaa** [openai/openai-cookbook#427]
[optional template]

**Is your feature request related to a problem? Please describe.**
We are not able right now to fine tune an openai model for multi-label classification. 
**Describe the solution you'd like**
It would be beneficial to have a notebook example on how to fine-tune an openai model for multi-label classification problems
 (I mean having more than one label in the completion part)

same as here https://github.com/openai/openai-cookbook/blob/main/examples/Fine-tuned_classification.ipynb
@BorisPower 

**Additional context**
No additional context

**Comment by ted-at-openai** [comment]
Definitely a thing that can be done. I do not have the time to write a notebook example. Take a look at https://docs.google.com/document/d/1rqj7dkuvl7Byd5KQPUJRxc19BJt8wo0yHNwK84KfU3Q/edit

**Comment by dylan904** [comment]
@ted-at-openai Not seeing anywhere in this documentation you have referred to that demonstrates how you might approach training a model that can have more than one label for classification at a time.
