### ISSUE TITLE
A Visually Impaired User's Request for Assistance with ChatGPT Account Access

### ISSUE THREAD

**Issue by Sysking1024** [openai/openai-cookbook#428]
Hello!
I am a visually impaired user (blind), and my main purpose of using ChatGPT software is to explore the prospects of the software in visual assistance. This software is very important to me, it helps me understand the information I want to know in an unprecedented way. For example, in the process of programming, I often encounter places that I don't understand or make mistakes. Due to my visual impairment, it is relatively inefficient for me to find answers through search engines, and some content is presented in the form of pictures. However, ChatGPT interacts with me in a conversational way and provides me with text descriptions so that I can immediately hear the information and knowledge I need through a screen reader. This conversational interaction makes me feel very excited and satisfied. However, a few months ago I encountered some problems. I found that I could not log in and showed that I had no permission. I was very confused because in my impression, I had never done any inappropriate behavior. I hope you can understand my situation and help me solve this problem.

If you need to provide any additional information or documents, I am willing to cooperate. In addition, in future use, I will continue to use ChatGPT and API in accordance with regulations. I will abide by OpenAI's usage regulations and maintain a good network environment. Thank you for your help and look forward to your reply🍻.

**Comment by dinavod12** [comment]
I recommend reaching out to the support team or the administrators of the software you're using to address the login issue. They should be able to assist you and provide the necessary permissions to access the software

**Comment by Sysking1024** [comment]
I have contacted OpenAI's support mailbox before creating this question,
but I didn't get a response, can you help me🍻

Rudra Pratap ***@***.***> 于2023年5月18日周四 13:04写道：

**Comment by ted-at-openai** [comment]
I'm sorry about your situation but this repo is not the right place. Recommend contacting support.
