### ISSUE TITLE
Feature request: Add embeded data file for testing/evaluating

### ISSUE THREAD

**Issue by Tenoke** [openai/openai-cookbook#43]
We can hit the API and create it ourselves but a pre-included file like embedded_1k_reviews.csv would make evaluating, following the API, testing what analysis might be worth it etc. more straightforward.

**Comment by ted-at-openai** [comment]
Will add soon. Thanks!

**Comment by ted-at-openai** [comment]
Added here (https://github.com/openai/openai-cookbook/blob/main/examples/data/fine_food_reviews_with_embeddings_1k.csv) in PR #66 and updated examples to use the precomputed embeddings. Let me know if you think anything more will be helpful. Will close now.
