### ISSUE TITLE
api_request_parallel_processor.py: results are in disorders

### ISSUE THREAD

**Issue by JeremyMeissner** [openai/openai-cookbook#456]
**File problem:**
[examples/api_request_parallel_processor.py](https://github.com/openai/openai-cookbook/blob/cfb1927cc3298554e5d7ef2934c6dfa015bf2418/examples/api_request_parallel_processor.py)

**Problem:**
The script `api_request_parallel_processor.py` return the results in disorders, which is really inconvenient when I have 26,000 async requests.

I'm using the `gpt-3.5-turbo` model

**Solution?**
Should I add an index in the message, so I can get back the same order at the end? Or is there a way to fix this issue?

**Comment by ted-at-openai** [comment]
Yep, parallel processing does not return results in order.

Option 1:
- use the input as the key

Option 2:
- use the recently added metadata field to store row order: https://github.com/openai/openai-cookbook/pull/448
