### ISSUE TITLE
[SUPPORT] Is there a way to provide theme coloring for the code blocks produced by ChatGPT?

### ISSUE THREAD

**Issue by fisheva** [openai/openai-cookbook#463]
Dear OpenAI,

I am writing this letter to express my sincere gratitude for the tremendous help ChatGPT has provided for my work and everyday life. I enjoyed using it immensely.

I am the author of [Eva Theme for VSCode](https://marketplace.visualstudio.com/items?itemName=fisheva.eva-theme&ssr=false#overview). I would like to provide theme coloring for the code blocks produced by ChatGPT. I believe that this could help enhance the user experience for ChatGPT a little bit. I wonder if there is a way to do this?

I have compared ChatGPT's theme to my Eva Dark and Eva Light themes. Images for comparison are provided at the end.

I would be grateful if you could send me any instructions or provide me with any resources or documentation that can help me achieve this.

Thank you again for your great creation, and I look forward to hearing from you soon. I appreciate any instructions or resources you can provide me with.

---

**Original ChatGPT webpage screenshot**
![origin](https://github.com/openai/openai-cookbook/assets/17448419/2475802b-946b-4cae-a13c-3e7201167a69)

**ChatGPT with Eva Dark (by PS)**
![EvaDark](https://github.com/openai/openai-cookbook/assets/17448419/23c4a1ca-52f0-4a4b-a06c-c4d33f4999c0)

**ChatGPT with Eva Light (by PS)**
![EvaLight](https://github.com/openai/openai-cookbook/assets/17448419/49d3e2e2-b654-4903-ae4d-129682b7d214)

**Direct comparison images of three code blocks**

![code-1-4](https://github.com/openai/openai-cookbook/assets/17448419/536895b3-6c6a-49d1-bac1-1658dc75be8e)
![code-2-3](https://github.com/openai/openai-cookbook/assets/17448419/c86e69da-37cd-49dc-8184-816e757b2ddc)
![code-3-3](https://github.com/openai/openai-cookbook/assets/17448419/c7c93f66-318c-4cbe-99af-cf7da4a3719b)

**Comment by ted-at-openai** [comment]
Appreciate the thinking, but unfortunately this repo is not the right place.

**Comment by fisheva** [comment]
Sorry, may I ask which repo should I raise this issue in?
