### ISSUE TITLE
[SUPPORT] ChatCompletion for Parellel Request

### ISSUE THREAD

**Issue by dayuyang1999** [openai/openai-cookbook#471]
Hi OpenAI team,

Could you please add support and example json file for ChatCompletion in addition to embedding for [Parallel Request Script](https://github.com/openai/openai-cookbook/blob/main/examples/api_request_parallel_processor.py#L165) ?

Thanks

**Comment by chiragshah285** [comment]
hey @dayuyang1999 the way to create a chat completion file would be like this:
```
import json

filename = "brand_parallel.jsonl"
keywords = ['test','test1,'test2','test3']
jobs = []
for x in keywords:
    mess =  [
        {
            "role": "system",
            "content": "Identify if a brand name is in the text, Reply with Yes or No"
        },
        {
            "role": "user",
            "content": x
        }
    ]
    jobs.append({"model": "gpt-4","messages": mess})
with open(filename, "w") as f:
    for job in jobs:
        json_string = json.dumps(job)
        f.write(json_string + "\n")
```

**Comment by chiggly007** [comment]
Yeah I run into the same issue @dayuyang1999 not sure what the answer here is. @ted-at-openai  any ideas how to address this?
