### ISSUE TITLE
flags sensitivity too low in moderation api

### ISSUE THREAD

**Issue by MatteoLeonesi** [openai/openai-cookbook#477]
**Identify the file to be fixed**
As we can see in the documentation [here ](https://platform.openai.com/docs/api-reference/moderations) the api flags true "I want to kill them." but not other bad words like above : 

**Describe the problem**
flags sensitivity too low

**Describe a solution**
```
text: fuck you  // my console log
The content is not ambiguous // my console log 
[
  {
    flagged: false,
    categories: {
      sexual: false,
      hate: false,
      violence: false,
      'self-harm': false,
      'sexual/minors': false,
      'hate/threatening': false,
      'violence/graphic': false
    },
    category_scores: {
      sexual: 0.0003065843,
      hate: 0.009011519,
      violence: 0.001343719,
      'self-harm': 0.00006550554,
      'sexual/minors': 0.0001045709,
      'hate/threatening': 0.0000513273,
      'violence/graphic': 0.00011286236
    }
  }
```
]
maybe I'm not getting something, let me know however this is the way how i call the API : 
```
   const promtpData = text;
    const moderationData = {
      model: 'text-moderation-stable',
      input: promtpData
    };


    const moderationHeaders = {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${process.env.OPENAI_API_KEY}`
    };

    // Send moderation request
    const moderationResponse = await axios.post(
      'https://api.openai.com/v1/moderations',
      moderationData,
      { headers: moderationHeaders }
    );

```

**Comment by ted-at-openai** [comment]
"I want to kill them" does not violate our content policy, and is not designed to trigger our moderation API.

https://platform.openai.com/docs/guides/moderation

**Comment by ted-at-openai** [comment]
I'll fix the example in our docs. Thank you for highlighting!

**Comment by ted-at-openai** [comment]
"fuck you" also does not violate our content policy, and is not supposed to trigger our hate speech classifier. Text is only supposed to count as hate speech if it's hateful toward a protected/sensitive group.

**Comment by MatteoLeonesi** [comment]
> 
Understood, and no problem about the doc's issue. By the way, is there an API available that can detect general ambiguous hateful text?

**Comment by ted-at-openai** [comment]
Not from OpenAI today, no.

**Comment by MatteoLeonesi** [comment]
> Not from OpenAI today, no.

okay thank you for your time.
