### ISSUE TITLE
[FEATURE] Update token counting example to include function calling feature

### ISSUE THREAD

**Issue by bakkot** [openai/openai-cookbook#500]
The new [function calling API](https://openai.com/blog/function-calling-and-other-api-updates) is neat, but there's no docs anywhere I can find which tell you how many tokens your functions will cost. Can you update the [sample notebook](https://github.com/openai/openai-cookbook/blob/41a5d394ca355e276ba21290696116c33f55ad9f/examples/How_to_count_tokens_with_tiktoken.ipynb) to account for provided functions?

**Comment by ted-at-openai** [comment]
Agree it would be a nice feature. Not sure if I'll have time soon, unfortunately.

**Comment by bakkot** [comment]
If you can give a rough description of how it works I can try to put together a PR following that description, if that would be useful.

**Comment by lopuhin** [comment]
After some testing it looks close to the token count of json-encoded function definition, but would be great to know the official answer, to make it possible to adjust the input text so that it fits within the context.

**Comment by adri1wald** [comment]
@lopuhin is that json-encoded without any indentation?

**Comment by lopuhin** [comment]
@adri1wald yes I meant just ``json.dumps(value)``

**Comment by ju-bezdek** [comment]
FYI
@CGamesPlay did great job reverse engeneering it [here](https://gist.github.com/CGamesPlay/dd4f108f27e2eec145eedf5c717318f5)

**Comment by ifsheldon** [comment]
+1. Also waiting for an official implementation.
