### ISSUE TITLE
[SUPPORT] Is the tiktoken calculation method of the 0613 model the same as the 0301 model?

### ISSUE THREAD

**Issue by quzard** [openai/openai-cookbook#502]
https://github.com/openai/openai-cookbook/blob/main/examples/How_to_count_tokens_with_tiktoken.ipynb

**Comment by averykhoo** [comment]
based on `usage.prompt_tokens` and adjusting the constants, it seems to exactly match the calculation method for `gpt-4-0314`. i'd still like an official confirmation if possible though

**Comment by averykhoo** [comment]
update: opened PR #511
