### ISSUE TITLE
[SUPPORT] Advice regarding SQL generation

### ISSUE THREAD

**Issue by avin-kavish** [openai/openai-cookbook#506]
> Note: SQL generation use cases are high-risk in a production environment - models can be unreliable when generating consistent SQL syntax. A more reliable way to solve this problem may be to build a query generation API that takes the desired columns as input from the model.

I saw this quote in your new function calling cookbook example. The idea of a query generation API, is it based on a successful implementation or theory?

> takes the desired columns as input from the model

The problem I've run into is SQL doesn't just retrieve columns from tables. Any non-trivial analysis would use aggregated metrics like avg, sum along with group by clauses. Advanced analysis would use things like `row_number(), having, cross join, CTEs` 

As an example, here's a query to retrieve the best performing product in a category from the [adventureworks sample database](https://github.com/morenoh149/postgresDBSamples/tree/master/adventureworks).

```sql
WITH ranked_products AS (
  SELECT
    pc.name AS category_name,
    p.name AS product_name,
    p.productnumber,
    SUM(sod.orderqty * sod.unitprice) AS total_sales_amount,
    ROW_NUMBER() OVER (PARTITION BY pc.name ORDER BY SUM(sod.orderqty * sod.unitprice) DESC) AS rank
  FROM
    production.product AS p
    INNER JOIN production.productsubcategory AS psc ON p.productsubcategoryid = psc.productsubcategoryid
    inner join production.productcategory as pc on pc.productcategoryid = psc.productcategoryid
    INNER JOIN sales.salesorderdetail AS sod ON p.productid = sod.productid
  GROUP BY
    pc.name,
    p.name,
    p.productnumber
)
SELECT
  category_name,
  product_name,
  productnumber,
  total_sales_amount
FROM
  ranked_products
WHERE
  rank = 1;
```

If you have ideas on how to create a query generation API that can accept some input and output something like this I'd love to hear.

**Comment by rzsgrt** [comment]
Hi, I think langchain have blog about query generation idea and how to do it using their framework [see here](https://blog.langchain.dev/llms-and-sql/).  

``` Any non-trivial analysis would use aggregated metrics like avg, sum along with group by clauses. Advanced analysis would use things like row_number(), having, cross join, CTEs```. 

I'm not sure about cte but row_number and aggregated metrics seems doable. I think important part here: you feed llm your table structure like column name and its datatype. and have specific prompt. 

For example if you want to `retrieve the best performing product in a category` then you need to define `best performing product` 

Hope this helps!

**Comment by avin-kavish** [comment]
I am already using the techniques described in the article, that's how I generated that example you see.

But the point OpenAI has made in the quote is - those techniques aren't accurate enough for production and there maybe a better way to implement it using a "query generation api".

So I was asking whether that's a theory or someone has actually made something like that.

**Comment by rzsgrt** [comment]
I see. so I try call functions implementation and compare with langchain implementation. One thing I notice is: In openai call functions (snippet below), it seems like we didn't feed llm what's available column to query (thats why they say `takes the desired columns as input from the model` ). 
```python
messages.append({"role": "system", "content": "Answer user questions by generating SQL queries against the Chinook Music Database."})
messages.append({"role": "user", "content": "Hi, who are the top 5 artists by number of tracks?"})
```


meanwhile in langchain implementation they state this in their prompt:  

```
Only use the following tables:
{table_info}
```
Table info here retrieved from create table statement, to there's column name, data type and relation with other table
and also they stated here:
```
Given an input question, first create a syntactically correct {dialect} query to run .... 
```
Meaning that syntax always in your sql dialect. For full prompt they use: [link](https://github.com/hwchase17/langchain/blob/560c4dfc98287da1bc0cfc1caebbe86d1e66a94d/langchain/chains/sql_database/prompt.py)


I think the langchain implementation already implement what open ai mention `query generation API that takes the desired columns as input from the model.`

But either openai/langchain implementation, I agree with this 
```
SQL generation use cases are high-risk in a production environment - models can be unreliable when generating consistent SQL syntax
```
and i think it takes big engineering effort to make it reliable

**Comment by avin-kavish** [comment]
Oh.
