### ISSUE TITLE
[PROBLEM] broken link

### ISSUE THREAD

**Issue by bartoncreek** [openai/openai-cookbook#516]
**File to be fixed:**

🡲  [`examples/How_to_call_functions_for_knowledge_retrieval.ipynb`](https://github.com/openai/openai-cookbook/raw/main/examples/How_to_call_functions_for_knowledge_retrieval.ipynb)

**Problem: Broken link (cell 1, line 3)**—

> This notebook builds on the concepts in the ⋯
> `[argument generation]('How_to_generate_function_arguments_with_chat_models.ipynb')`

**Solution:** this writer is uncertain of the intended target.

**Comment by ted-at-openai** [comment]
That's embarrassing. Fixed it. Thank you.
