### ISSUE TITLE
olympics-2-create-qa: That model does not exist

### ISSUE THREAD

**Issue by cbader** [openai/openai-cookbook#52]
I'm attempting to run olympics-2-create-qa.ipynb, but I'm getting the not-very-helpful error "That model does not exist", presumably referring to davinci-instruct-beta-v2.

**Comment by mxk1011** [comment]
Use `text-davinci-002` - some things in those examples are outdated. Search endpoint is deprecated and no more usable. Somebody should make an update to those examples.

**Comment by chaoranxie** [comment]
looks like we are suppose to use the code in this example https://github.com/openai/openai-cookbook/blob/main/examples/Question_answering_using_embeddings.ipynb

**Comment by ted-at-openai** [comment]
I highly recommend following the ideas in this notebook: https://github.com/openai/openai-cookbook/blob/main/examples/Question_answering_using_embeddings.ipynb

The fine-tuned Q&A example isn't great and relies on some out of date APIs. Sorry you ran into issues.
