### ISSUE TITLE
[PROBLEM] Missing `Using vector databases for embeddings search` blob

### ISSUE THREAD

**Issue by KernelBypass** [openai/openai-cookbook#570]
https://github.com/openai/openai-cookbook/blob/main/examples/vector_databases/Using_vector_databases_for_embeddings_search.ipynb

**Comment by ted-at-openai** [comment]
Where's that link from? We try to keep links alive, but may not always succeed.

**Comment by KernelBypass** [comment]
![image](https://github.com/openai/openai-cookbook/assets/62620821/2502a7d1-cdb9-412c-b0f4-e417c9d0e068)

**Comment by ted-at-openai** [comment]
Fixed it. Thanks!
