### ISSUE TITLE
[FEATURE]Could you please take a look at this project for creating LLM based Agent fast and embeddable into code logic

### ISSUE THREAD

**Issue by Maplemx** [openai/openai-cookbook#594]
I'm not sure if this is a suitable topic for the cookbook

We try to explain a new way to use LLM / Agent not only in some user products with UI, but also in code developing.

This is the project Agently: https://github.com/Maplemx/Agently , README doc explains the idea.

We aim to make application developers can generate a LLM based Agent instance(especially based on GPT version 3.5 and above) and use this instance like a function or a work node in their code.

Hope to get your reply. Thanks.

**Comment by Maplemx** [comment]
I can write some examples like "how to use agent instance to write a daily news brief" or "how to use a tagging agent to replace classic NLP content tagging work node" if it is suitable.

**Comment by simonpfish** [comment]
We'll be announcing a new process for contributing links to repos and project soon. Stay tuned.
