### ISSUE TITLE
Q&A with embeddings uses 4096 dimensions but updated API uses 1536

### ISSUE THREAD

**Issue by ScotterC** [openai/openai-cookbook#61]
Regarding https://github.com/openai/openai-cookbook/blob/main/examples/Question_answering_using_embeddings.ipynb

This only becomes a significant problem when trying to reproduce the tutorial because the olympics embeddings dataset [Olympics Embeddings CSV](https://cdn.openai.com/API/examples/data/olympics_sections_document_embeddings.csv) is 4096 dimensions. An easy fix would be to point to a 1536 dimension version so that readers don't need to regenerate it themselves.

**Comment by ted-at-openai** [comment]
Thanks! Will fix this week.

**Comment by ted-at-openai** [comment]
Now fixed. Closing the issue, but let me know if you run into any further problems.
