### ISSUE TITLE
This omits *characters*, not *lines* from the file names.

### ISSUE THREAD

**Issue by Cadence-GitHub** [openai/openai-cookbook#635]
https://github.com/openai/openai-cookbook/blob/4912564dc16745c9376e2b1f78c80cb1bab73f01/apps/web-crawl-q-and-a/web-qa.py#L190C41-L190C41

It would be better if these numbers were dynamically adjusted from the `domain` string, for example:
`texts.append((file[len(domain)+1:-4].replace('-',' ').replace('_', ' ').replace('#update',''), text))`

Same with the last 3 characters. It might be something like:
```
parts = domain.split('.')
number_of_characters_after_dot = len(parts[1])
```

**Comment by Cadence-GitHub** [comment]
You can do it like this: https://github.com/Cadence-GitHub/openai-cookbook/pull/1

**Comment by simonpfish** [comment]
I agree, thank you for the pointer! Keeping this in the record for @logankilpatrick to potentially incorporate in the future.
