### ISSUE TITLE
Unable to fetch embeddings for the custom dataset 

### ISSUE THREAD

**Issue by sathvik2612** [openai/openai-cookbook#65]
I am unable to fetch the embeddings for the custom dataset. So please go through this and let me know the mistakes.

https://colab.research.google.com/drive/1tDbGALx0wdgq8qg4zF8qKCMrQwioQ3Vk?usp=sharing

**Comment by sathvik2612** [comment]
I am applying for fake news prediction dataset, it is providing embeddings for amazon reviews dataset.

**Comment by ted-at-openai** [comment]
I don't see anything at this link. Can you share more context?

**Comment by sathvik2612** [comment]
I solved it.
