### ISSUE TITLE
[SUPPORT] Issue with Re-Fine Tuning a Fine-Tuned GPT-3 Model - Model Not Available Error

### ISSUE THREAD

**Issue by tarekbadrshalaan** [openai/openai-cookbook#657]
**Description**:
I have encountered an issue while trying to re-fine tune a GPT-3 model that I previously fine-tuned. When attempting to create a new fine-tuning job using the code below, I received an error message stating that the model is not available for fine-tuning or does not exist.

**Code Snippet**:
```python
import openai

openai.api_key = "sk-qEsC....."

response = openai.FineTuningJob.create(training_file="file-NEK......",
                                       model="ft:gpt-3.5-turbo-0613:tar....MFz",
                                       suffix="TR....H",
                                       )
```

**Code Snippet**:
```
openai.error.InvalidRequestError: Model ft:gpt-3.5-turbo-0613:tar....MFz is not available for fine-tuning or does not exist.
```

**Comment by tarekbadrshalaan** [comment]
After reviewing the latest OpenAI documentation, I've discovered that continuing the fine-tuning process on a model that has already been fine-tuned (re-fine tuning) is not currently supported.

The [documentation](https://platform.openai.com/docs/guides/fine-tuning/can-i-continue-fine-tuning-a-model-that-has-already-been-fine-tuned) explicitly states:

> "Can I continue fine-tuning a model that has already been fine-tuned? No, we do not currently support continuing the fine-tuning process once a job has finished. We plan to support this in the near future."

Given this information, it appears that my original request is not feasible at this time. I look forward to the future support of this feature, as it would greatly enhance our ability to optimize models for specific tasks.


<img width="934" alt="image" src="https://github.com/openai/openai-cookbook/assets/31471186/e57064d1-4a79-41b4-a543-75396caf178b">

**Comment by logankilpatrick** [comment]
Correct, we do not support fine-tuning existing fine-tuning jobs yet with the new API. Stay tuned!
