### ISSUE TITLE
[PROBLEM]Fine-tuning notebook doesn't have the method defined

### ISSUE THREAD

**Issue by jameszhucigna** [openai/openai-cookbook#658]
https://github.com/openai/openai-cookbook/blob/main/examples/How_to_finetune_chat_models.ipynb 

This notebook is great, but has a section like below:

```
test_row = test_df.iloc[0]
test_messages = []
test_messages.append({"role": "system", "content": system_message})
user_message = create_user_message(test_row)
test_messages.append({"role": "user", "content": create_user_message(test_row)})

pprint(test_messages)
```

Where `test_df` and `create_user_message` cannot be found in the whole noteobok or in the repo. `test_df` can easily be constructed but seems like `create_user_message` isn't there.

**Comment by simonpfish** [comment]
fixed by #660
