### ISSUE TITLE
How to properly use logit_bias

### ISSUE THREAD

**Issue by Clement-Lelievre** [openai/openai-cookbook#677]
### Discussed in https://github.com/openai/openai-cookbook/discussions/676

<div type='discussions-op-text'>

<sup>Originally posted by **Clement-Lelievre** September  4, 2023</sup>
Reposting [my issue](https://github.com/openai/tiktoken/issues/183) on Tiktoken's repo

I need to use the openAI Chat endpoint and **prevent some words from appearing in the model's completion**. 
To achieve this, I use the [`logit_bias` ](https://platform.openai.com/docs/api-reference/chat/create#logit_bias) parameter, which expects a mapping of tokens to an int value (-100 in my case). This is where **tiktoken** comes in.

PROBLEM: the forbidding mechanism described above works at token-level, not at word-level. Therefore, and because some tokens are shared across words, forbidding a token with a specific word in mind can result in unintended consequences, namely forbidding other words in the process.

EXAMPLE: I want the model's completion to NOT include the word "**impossible**". The tokens for this word as per `cl100k_base` are: `[318, 10236]` . So I pass to my openai query: `logit_bias = {318 : -100, 10236 : -100}` . However, because the token list for the word "possible" using the same encoder is : `[10236]` this could result in an unwanted ban of the word "**possible**".</div>

**Comment by jeffswt** [comment]
GPT being a decoder-only model has an inference mechanism that respects generated tokens as a prefix of the next result. Treating it as an optimizer that runs forever on a freeform grammar, where each state leads to another state that simply adds an arbitrary next token, setting `logit_bias` on a token to `-100` would eradicate all branches (on this grammar) whose ancestors contain this token. It is therefore not possible to only eliminate the word *impossible*, without affecting either *possible* or all words prefixed with *im-*.

There is, however, one solution that can achieve your requirements, at the cost of extra latency (at least 3x) and input token cost:

1. Decode with `end_token` set to the prefix ` im`.
2. Attempt to retrieve the next 2 tokens with this new prefix (i.e. include the incomplete text generated by the assistant).
3. Should the next 2 tokens concatenate into ` impossible`, do not attempt to add these 2 tokens into the history. Generate exactly 1 token again, with the token ` im` banned, based on the output from Step 1.
4. Goto Step 1, this time (as it had) without any `logit_bias` set.

In this way you can totally avoid the word *impossible* without impacting the word *possible* or any word starting with the prefix *im-*. But as I said, it could be expensive.
