### ISSUE TITLE
OPENAİ

### ISSUE THREAD

**Issue by Efereyis** [openai/openai-cookbook#680]
const Discord = require("discord.js");
const { OpenAIApi } = require("openai");

const client = new Discord.Client();
const openai = new OpenAIApi("YOUR_OPENAI_API_KEY"); // OpenAI API anahtarını buraya yerleştirin

client.on("ready", () => {
  console.log(`Bot ${client.user.tag} olarak giriş yaptı.`);
});

client.on("message", async (message) => {
  if (message.author.bot) return;

  if (message.content.toLowerCase() === "bot") {
    try {
      const response = await openai.complete({
        prompt: "Konuşma başlat: ",
        max_tokens: 50,
      });
      message.channel.send(response.choices[0].text.trim());
    } catch (error) {
      console.error("OpenAI isteği sırasında bir hata oluştu:", error);
    }
  }
});

client.login("YOUR_DISCORD_BOT_TOKEN"); // MTEyNDM5NTMxMDgwNzAwNzI0Mg.GvCMa2.kAXBoZUWee16HyMRisKzN3U3JqMPYSuDt3uZ2w

**Comment by simonpfish** [comment]
@Efereyis you might want to rotate that discord bot token
