### ISSUE TITLE
Rate limit reached only 60/min current 100/min

### ISSUE THREAD

**Issue by sathvik2612** [openai/openai-cookbook#70]
code: df['davinci'] = df.title.apply(lambda x: get_embedding(x, engine='text-similarity-davinci-001'))

RateLimitError: Rate limit reached for default-global-with-image-limits in organization org-1UIBeDGivAGB5s2IeBxupqGD on requests per min. Limit: 60.000000 / min. Current: 100.000000 / min. Contact [support@openai.com](mailto:support@openai.com) if you continue to have issues.

**Comment by sathvik2612** [comment]
I also would like to know whether engine='text-similarity-davinci-001' will provide the same vector size for every different length of words and sentences?

**Comment by ted-at-openai** [comment]
I recommend using `text-embedding-ada-002` it's better and far cheaper than `text-similarity-davinci-001`. See more here: https://openai.com/blog/new-and-improved-embedding-model/

This guide gives advice on rate limits: https://github.com/openai/openai-cookbook/blob/main/examples/How_to_handle_rate_limits.ipynb
