### ISSUE TITLE
 Retry from ID of previous API request?

### ISSUE THREAD

**Issue by gnmarten** [openai/openai-cookbook#74]
ChatGPT made me believe this exists,

![retry](https://user-images.githubusercontent.com/4067316/212356904-b457ed86-b802-4e56-ada2-cd0dbe336ad5.png)

I might have reached a rate limit, but something like this could be useful in case of connection loss or other mishaps. 

Is this possible?

**Comment by ted-at-openai** [comment]
ChatGPT lies about all sorts of stuff. Don't trust it blindly. :)
