### ISSUE TITLE
[FEATURE] - Outline for a notebook about function calling with the Node SDK

### ISSUE THREAD

**Issue by perborgen** [openai/openai-cookbook#743]
I would like to write a notebook about function calling using the Node SDK. Here is a [4-minute screencast that explains the article idea](https://scrimba.com/scrim/co996432f91b2947d6a95bfb3) in detail.

**Is your feature request related to a problem? Please describe.**
Almost all notebooks are based on Python. However, there are tons of JavaScript developers who use the OpenAI API as well. These people lack good tutorials, [as exemplified by this post](https://community.openai.com/t/function-calling-in-node-js/267742) in the OpenAI community forum.

**Describe the solution you'd like**
I will write a draft of the article and submit it as a PR. I have more than 5 years of experience teaching developers via text and video courses, so you can trust that the quality will be up to your standards.

**Comment by simonpfish** [comment]
Would love this content! Feel free to submit a PR

**Comment by simonpfish** [comment]
Sorry, accidentally closed.
