### ISSUE TITLE
Output sometimes terminates in the middle of generating a response

### ISSUE THREAD

**Issue by Eric-Shotwell** [openai/openai-cookbook#75]
Output sometimes terminates in the middle of generating a output.

There should be a way to duplicate the previous output. Is there? 

This is my first time using GitHub... Am I doing it right?...

**Comment by ted-at-openai** [comment]
Can you provide more details, please? What are you running? What's terminating?

**Comment by Eric-Shotwell** [comment]
> Can you provide more details, please? What are you running? What's terminating?

I've encountered it on both: 
Windows 10 (Google Chrome) 
Android (Opera)

It will be generating text, and stops during output when there obviously should/was more. 

It happens randomly, so I can't really reproduce it or generate the output again. One prompt might cause it to happen, and then the same prompt doesn't.

It only seems to be on longer output though (granted, a shorter output would give less time for it to happen, but I haven't noticed it yet).

**Comment by ted-at-openai** [comment]
Closing this issue as I still don't know what you're running or what's terminating. Happy to help if you can explain in more detail.

**Comment by Eric-Shotwell** [comment]
> Closing this issue as I still don't know what you're running or what's terminating. Happy to help if you can explain in more detail.

I've encountered it on both: 
Windows 10 (Google Chrome) 
Android (Opera)

It will be generating text, and stops during output when there obviously should/was more. 

Was more needed? Sorry, I'm new at this...
