### ISSUE TITLE
how do I generate this embedded_babbage_similarity_50k dataset

### ISSUE THREAD

**Issue by dsl2022** [openai/openai-cookbook#76]
from the  User and product embeddings notebook, it specified that the data was obtained by using the Obtain_dataset.ipynb, but I do not see how it can generate that and nor did I find any other place has this dataset. Please let me know how I can get it. thanks.

**Comment by ted-at-openai** [comment]
Currently it's left as an exercise to the reader. I'll try to add something next week.

**Comment by ted-at-openai** [comment]
I'm going to close this because I don't think we're going to get to it, unfortunately. Best wishes.
