### ISSUE TITLE
module 'openai' has no attribute 'Embedding'

### ISSUE THREAD

**Issue by vinceallenvince** [openai/openai-cookbook#78]
When trying to run the first cell of the [embeddings example](https://github.com/openai/openai-cookbook/blob/main/examples/Get_embeddings.ipynb):

```
import openai

embedding = openai.Embedding.create(
    input="Your text goes here", model="text-embedding-ada-002"
)["data"][0]["embedding"]
len(embedding)
```

I get this error:

`AttributeError: module 'openai' has no attribute 'Embedding'`

I've tried updating my openai install with:

`pip install --upgrade openai`

I've also run:

`pip install openai[embeddings]`

However, I still can't get past the error. Any help would be greatly appreciated! Thanks.

**Comment by vinceallenvince** [comment]
Ah, I figured it out. I had some issues with my virtual environment using an older version of Python. Now that I'm on 3.10 it's working fine. Thanks!

**Comment by codemaker2015** [comment]
Try to use openai version 0.28.1

`pip install openai==0.28.1`

**Comment by p1kn1t** [comment]
@codemaker2015 thanks that fixed it for me.
