### ISSUE TITLE
[PROBLEM] "How to use the DALL E API" yields 502 error (body too large) 

### ISSUE THREAD

**Issue by askmeegs** [openai/openai-cookbook#799]
[optional format]

**Identify the file to be fixed**
The name of the file containing the problem.

https://cookbook.openai.com/examples/dalle/image_generations_edits_and_variations_with_dall-e

**Describe the problem**

Hitting that URL in a browser yields a 502 error. Perhaps due to large image file sizes?

**Describe a solution**
A clear and concise description of what a fixed version should do.

**Screenshots**

<img width="613" alt="Screenshot 2023-10-18 at 1 58 02 PM" src="https://github.com/openai/openai-cookbook/assets/3137106/8fd451a5-d3b3-4117-aebc-e836dbdc7ae9">

**Additional context**

**Comment by simonpfish** [comment]
Thank you for reporting! We'll look into it
