### ISSUE TITLE
[DOCS]: Adding Code_Of_Conduct to repo

### ISSUE THREAD

**Issue by mohitd404** [openai/openai-cookbook#813]
code-of-conduct:- We propose adding a comprehensive Code of Conduct to our repository to ensure
 a safe, respectful, and inclusive environment for all contributors and users. This code will 
serve as a guideline for behavior, promoting diversity, reducing conflicts, 
and attracting a wider range of perspectives.

**Issue type**

- [✅] Docs

**Additional context**

@Capin-daddy @simonpfish If you were planning this issue kindly assign it to me! I would love to work on it ! Thank you !

**Comment by Panquesito7** [comment]
I believe this issue should probably be closed now that the PR was rejected.
