### ISSUE TITLE
[PROBLEM]

### ISSUE THREAD

**Issue by munirjojoverge** [openai/openai-cookbook#824]
[optional format]

**Identify the file to be fixed**
Every file containing "ChatCompletion"

**Describe the problem**
In the very late openai package "ChatCompletion" has been changed by "completion" and there are also some changes on the ".create"

**Describe a solution**
Update all "ChatCompletion" and the parameters passed to it since "completion" has a different signature.

**Comment by 0hq** [comment]
Thanks for the heads up! We're working on this now.
