### ISSUE TITLE
OpenAI Chatcompletion dataSources issue

### ISSUE THREAD

**Issue by Kunal93v** [openai/openai-cookbook#825]
``I am getting unrecognized request argument error while trying to use bring your own data using API calling. Below is the error and the code I am using, please help. Thanks in advance!

### Error: 

**openai.error.InvalidRequestError: Unrecognized request argument supplied: dataSources**

### Here's my code:

`import os
import openai
import dotenv
from azure.identity import DefaultAzureCredential
import typing
import time
import requests

dotenv.load_dotenv()

openai.api_base = os.environ["OPENAI_API_BASE"]
openai.api_version = "2023-08-01-preview"
use_azure_active_directory = False  

if not use_azure_active_directory:
    openai.api_type = 'azure'
    openai.api_key = os.environ["OPENAI_API_KEY"]

if use_azure_active_directory:
    default_credential = DefaultAzureCredential()
    token = default_credential.get_token("https://cognitiveservices.azure.com/.default")

    openai.api_type = "azure_ad"
    openai.api_key = token.token

if typing.TYPE_CHECKING:
    from azure.core.credentials import TokenCredential

class TokenRefresh(requests.auth.AuthBase):

    def __init__(self, credential: "TokenCredential", scopes: typing.List[str]) -> None:
        self.credential = credential
        self.scopes = scopes
        self.cached_token: typing.Optional[str] = None

    def __call__(self, req):
        if not self.cached_token or self.cached_token.expires_on - time.time() < 300:
            self.cached_token = self.credential.get_token(*self.scopes)
        req.headers["Authorization"] = f"Bearer {self.cached_token.token}"
        return req

def setup_byod(deployment_id: str) -> None:

    class BringYourOwnDataAdapter(requests.adapters.HTTPAdapter):

        def send(self, request, **kwargs):
            request.url = f"{openai.api_base}/openai/deployments/{deployment_id}/extensions/chat/completions?api-version={openai.api_version}"
            return super().send(request, **kwargs)

    session = requests.Session()

    # Mount a custom adapter which will use the extensions endpoint for any call using the given `deployment_id`
    session.mount(
        prefix=f"{openai.api_base}/openai/deployments/{deployment_id}",
        adapter=BringYourOwnDataAdapter()
    )

    if use_azure_active_directory:
        session.auth = TokenRefresh(default_credential, ["https://cognitiveservices.azure.com/.default"])

    openai.requestssession = session

setup_byod("GPT432k")

response = openai.ChatCompletion.create(
    messages=[{"role": "user", "content": "What are the differences between Azure Machine Learning and Azure AI services?"}],
    deployment_id="GPT432k",
    dataSources=[
        {
            "type": "AzureCognitiveSearch",
            "parameters": {
                "endpoint": os.environ["SEARCH_ENDPOINT"],
                "key": os.environ["SEARCH_KEY"],
                "indexName": os.environ["SEARCH_INDEX_NAME"],
            }
        }
    ],
    stream=True,
)

for chunk in response:
    delta = chunk.choices[0].delta

    if "role" in delta:
        print("\n"+ delta.role + ": ", end="", flush=True)
    if "content" in delta:
        print(delta.content, end="", flush=True)
    if "context" in delta:
        print(f"Context: {delta.context}", end="", flush=True)`

**Comment by jerry-casuga-orica** [comment]
Also encountering this issue. Code is unchanged and this error appeared out of nowhere.

**Comment by kristapratico** [comment]
@Kunal93v @jerry-casuga-orica That error occurs when `dataSources` is passed, but the non-extensions chat completions endpoint is targeted. If running in the notebook, I would restart and make sure that the code setting up the adapter is called.

Also want to add that if you're able, it would be great to migrate to v1 of the openai library. This version doesn't require you to set up the adapter and includes other benefits illustrated here: https://github.com/openai/openai-python/discussions/742

Here's the cookbook using the v1 library to call bring your own data: https://github.com/openai/openai-cookbook/blob/dfd3cf8fd94341d2a0c28eab70a85dc6979d2d71/examples/azure/v1/chat_with_your_own_data.ipynb

**Comment by aiwithaditya** [comment]
Hi,
I will let you know the issue:
1.Simply close the session and re-run the Jupyter Notebook. This should resolve the issue.
2.Alternatively, you can switch entirely to .py scripts, which will not have this issue.
