### ISSUE TITLE
openai.error.RateLimitError: Request too large for gpt-4-vision-preview => but I am sure I have a limit ! 

### ISSUE THREAD

**Issue by ihorrible** [openai/openai-cookbook#842]
Hi ! I followed the example (https://cookbook.openai.com/examples/gpt_with_vision_for_video_understanding) with my different API keys from my three accounts and always have the same error for the following line of code => result = openai.ChatCompletion.create(**params): 

openai.error.RateLimitError: Request too large for gpt-4-vision-preview in organization org-TWxkcNkvywCuNqekVQZjD7o2 on tokens per min (TPM): Limit 20000, Requested 47463. The input or output tokens must be reduced in order to run successfully. Visit https://platform.openai.com/account/rate-limits to learn more.

I am sure I have a limit because my account is pretty new and does not have any heavy usage. 

Is it working stable? 

Thanks, 

Ivan

**Comment by getting55** [comment]
> 你好！我使用来自我的三个帐户的不同 API 密钥遵循示例 （https://cookbook.openai.com/examples/gpt_with_vision_for_video_understanding），并且对于以下代码行 => result = openai，总是出现相同的错误。ChatCompletion.create（**参数）：
> 
> openai.error.RateLimitError：组织 org-TWxkcNkvywCuNqekVQZjD7o2 中对每分钟令牌数 （TPM） 的 gpt-4-vision-preview 请求太大：限制 20000，请求 47463。必须减少输入或输出令牌才能成功运行。访问 https://platform.openai.com/account/rate-limits 了解更多信息。
> 
> 我确信我有一个限制，因为我的帐户很新，没有任何大量使用。
> 
> 它工作稳定吗？
> 
> 谢谢
> 
> 伊凡
Because the new model has a limit on the number of calls per day, there is also a maximum token limit per hour。
Other than that，
![Uploading 屏幕截图 2023-11-09 210522.png…]()
I can offer you discounted amounts, including GPT3.5, 4.0, the latest version of Preview, Vision, if you need to trust my price will make you tempted
