### ISSUE TITLE
429 Error You exceeded your current quota, please check your plan and billing details.

### ISSUE THREAD

**Issue by Kulaneian** [openai/openai-cookbook#844]
I have a pay as you go account and bought credits 2 days ago. I created a new API key right after and it has been 48 hours since then, but I keep getting the following error when I make an API request:

```json
{
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details.",
        "type": "insufficient_quota",
        "param": null,
        "code": "insufficient_quota"
    }
}
```

Any idea what could cause it?

**Comment by Kulaneian** [comment]
Turns out I had the API key open under my 'Personal' account, but I deposited funds with my 'Student' account. My bad

**Comment by getting55** [comment]
> I have a pay as you go account and bought credits 2 days ago. I created a new API key right after and it has been 48 hours since then, but I keep getting the following error when I make an API request:
> 
> ```json
> {
>     "error": {
>         "message": "You exceeded your current quota, please check your plan and billing details.",
>         "type": "insufficient_quota",
>         "param": null,
>         "code": "insufficient_quota"
>     }
> }
> ```
> 
> Any idea what could cause it?

I can offer you discounted amounts, including GPT3.5, 4.0, the latest version of Preview, Vision, if you need to trust my price will make you tempted
![Uploading 屏幕截图 2023-11-09 210522.png…]()

**Comment by l2aelba** [comment]
+ I have the same problem.

**Comment by getting55** [comment]
> ++++ I have the same problem.,insufficient_quota,How much credit do you need, if you need a large amount, 5k USD, I can provide you with a discount amount, of course, the same as the official website provides you

**Comment by Kulaneian** [comment]
The solution is in the dashboard on platform.openai.com. You need to set the 'Default organization' to the organisation you have purchased the credits with.

**Comment by kpitaldev2** [comment]
I have the same problem.

**Comment by SeaDude** [comment]
I had to add $ to my account to get past this error. I thought I was "just billed" but apparently I had to pay first. I don't use the API that much.
