### ISSUE TITLE
Update examples/utils/embeddings_utils.py to API V1

### ISSUE THREAD

**Issue by gaborcselle** [openai/openai-cookbook#855]
The file [examples/utils/embeddings_utils.py](https://github.com/openai/openai-cookbook/blob/main/examples/utils/embeddings_utils.py) needs to be updated to API V1. A number of related .ipynb notebooks are failing with depracation errors.

FIX: I have drafted a PR: [embeddings_utils_v1_fixes.diff](https://gist.github.com/gaborcselle/3bd5041fc4ba39e086b5207ca6ac2bcd#file-embeddings_utils_v1_fixes-diff) to fix this issue.

**Identify the file to be fixed**
* [examples/utils/embeddings_utils.py](https://github.com/openai/openai-cookbook/blob/main/examples/utils/embeddings_utils.py) and related `.ipynb` notebooks such as
* [examples/Classification_using_embeddings.ipynb](https://github.com/openai/openai-cookbook/blob/main/examples/Classification_using_embeddings.ipynb), 
* [examples/Zero-shot_classification_with_embeddings.ipynb](https://github.com/openai/openai-cookbook/blob/main/examples/Zero-shot_classification_with_embeddings.ipynb)
* ... and many others

**Describe the problem**
The embeddings_utils.py file has not been [updated to API V1](https://github.com/openai/openai-python/discussions/742) which causes a number of errors:

1. Uses `a*` methods such as `acreate`
2. Doesn't use new names, e.g. `openai.Embedding.create()` -> `client.embeddings.create()`
3. Uses `engine` keyword in function calls when it should use `model`

This causes a number of the example .ipynb notebooks to fail as well.

**Describe a solution**

1. Update embeddings_utils.py to API V1 per the [migration guide](https://github.com/openai/openai-python/discussions/742). 
2. Update related Python notebooks in the /examples/ directory.3. 

**Additional context**
I'd like push this diff as a PR: [embeddings_utils_v1_fixes.diff](https://gist.github.com/gaborcselle/3bd5041fc4ba39e086b5207ca6ac2bcd#file-embeddings_utils_v1_fixes-diff).

This diff includes updates for `embeddings_utils.py` and related `.ipynb` notebooks. I have manually tested all related `.ipynb` notebooks that import `embeddings_utils.py` and confirm that they work with API version 1.2.3.

**Comment by simonpfish** [comment]
Hi @gaborcselle! Thank you for flagging and fixing. You can open a PR by forking the repository. 

@jhills20 for visibility

**Comment by gaborcselle** [comment]
Great, working on that. PR coming shortly.

**Comment by gaborcselle** [comment]
PR is up, thanks @simonpfish and @jhills20!

**Comment by beshr-sab23** [comment]
Hi! 
I am getting an error when try to use utils.embeddings_utils
`from utils.embeddings_utils import get_embedding`
error: ModuleNotFoundError: No module named 'utils.embeddings_utils'

In Colab, I've ran `!pip install --upgrade openai` and `!pip install utils`

Does anyone know how to solve this error. Thanks

**Comment by danthedanman** [comment]
> Hi! I am getting an error when try to use utils.embeddings_utils `from utils.embeddings_utils import get_embedding` error: ModuleNotFoundError: No module named 'utils.embeddings_utils'
> 
> In Colab, I've ran `!pip install --upgrade openai` and `!pip install utils`
> 
> Does anyone know how to solve this error. Thanks

I am seeing the same error.

**Comment by beshr-sab23** [comment]
> > Hi! I am getting an error when try to use utils.embeddings_utils `from utils.embeddings_utils import get_embedding` error: ModuleNotFoundError: No module named 'utils.embeddings_utils'
> > In Colab, I've ran `!pip install --upgrade openai` and `!pip install utils`
> > Does anyone know how to solve this error. Thanks
> 
> I am seeing the same error.

Use this instead:
def get_embedding(text, model="text-embedding-ada-002"):
   text = text.replace("\n", " ")
   return client.embeddings.create(input = [text], model=model).data[0].embedding
   
resouces: https://platform.openai.com/docs/guides/embeddings/use-cases

**Comment by gaborcselle** [comment]
Thanks @beshr-sab23 and @danthedanman for flagging, I'll take a look at this tomorrow.

**Comment by gaborcselle** [comment]
@beshr-sab23 what directory is the file in that you are calling `from utils.embeddings_utils import get_embedding` from? that import statement will only work for .`ipynb` and `.py` files located in the /examples directory of the repo.

I just re-tested the import statement locally, with a current version of the repo's `main` branch, and works fine.

Thanks and let me know! Gabor

**Comment by Sagun15** [comment]
@gaborcselle I was trying to use the same command in colab notebook and facing the same issue. Module not found. 
<img width="692" alt="image" src="https://github.com/openai/openai-cookbook/assets/120552108/bc4364bc-7f14-4185-a884-a9ee3d0f71c8">
