### ISSUE TITLE
[PROBLEM] Inconsistent Deterministic Outputs with Seed Parameter in OpenAI API

### ISSUE THREAD

**Issue by hengqujushi** [openai/openai-cookbook#861]
**Identify the file to be fixed**
N/A - This issue is related to the OpenAI API's deterministic behavior when using the seed parameter.

**Describe the problem**
I am encountering an issue where I receive inconsistent outputs from the OpenAI API despite setting the same seed parameter for deterministic behavior. This is unexpected as the seed parameter is intended to ensure reproducibility of results. Both the System Fingerprint and the Seed values are identical for different requests, but the responses differ.

**Describe a solution**
A potential solution would be to investigate the determinism functionality within the OpenAI API when the seed parameter is set. Ensuring that the outputs are consistent across multiple requests with the same seed would resolve this issue.

**Screenshots**
![image](https://github.com/openai/openai-cookbook/assets/2217955/b5a761c2-0c7c-4b9d-be4f-ddd055a4d674)

**Additional context**
- The code is being run using the following notebook: https://github.com/openai/openai-cookbook/blob/main/examples/Deterministic_outputs_with_the_seed_parameter.ipynb 
- The issue persists across multiple attempts and different times, suggesting it is not an intermittent issue.
- No concurrent requests were made that could affect the outcome.

**Comment by tsilva** [comment]
I confirm that the same issue is happening to me as well.

- `model`: gpt-3.5-turbo-1106
- `temperature`: 0
- `seed`: 12345

Getting different responses each time, while getting the same `system_fingerprint`.

**Comment by lionelchg** [comment]
Same here

**Comment by jd-codelink** [comment]
Anybody able to reproduce the deterministic results?

**Comment by SovereignRemedy** [comment]
> Anybody able to reproduce(重现) the deterministic results?有人能够重现确定性结果吗？

The same problem was encountered at least two weeks ago, but no logical explanation has been seen so far

**Comment by SovereignRemedy** [comment]
Some problems that output few tokens may have a high probability of stable output，But the odds are less than 50%

**Comment by gaborcselle** [comment]
I believe this is actually an API issue, as reported here: https://github.com/openai/openai-python/issues/850

**Comment by chrispy-snps** [comment]
We have this issue too.

**Comment by yongyaoduan** [comment]
We have this issue too, who knows when this gets fixed?

**Comment by AayushSameerShah** [comment]
@yongyaoduan let me call Sam Altman, I will let you know.

**Comment by chrispy-snps** [comment]
Here is a script I wrote to plot the word similarity across _N_ OpenAI responses for one or more LLM parameter configurations:

[plot_openai_response_similarity.py](https://gist.github.com/chrispy-snps/0860612019bf6d873e6aa9f096967cb4)

Here is an example plot for four LLM configurations, with _N_=100 responses for each one:

![tell_me_a_story](https://github.com/openai/openai-cookbook/assets/50950969/975d053a-4d15-46dc-9790-33e63a3491a8)

The X axis indicates how far into the string is considered. The Y axis indicates similarity (higher is more similar).

The gist link has more details.

**Comment by ross-nordstrom** [comment]
Something to double check: the openai docs point out that `seed` is only supported on `gpt-4-1106-preview` and `gpt-3.5-turbo-1106`
https://cookbook.openai.com/examples/reproducible_outputs_with_the_seed_parameter

That said, my anecdotal experience matches what chrispy-snps showed -- the beginning of my response is the same across queries, but I get variety further into the response

**Comment by chrispy-snps** [comment]
This is useful discussion and it would be nice to keep it open a bit longer.

**Comment by boxabirds** [comment]
Still an issue.

**Comment by boxabirds** [comment]
Seems like the seed parameter still needs to be removed or fixed.

**Comment by gaborcselle** [comment]
@boxabirds did you still see this bug when you tried a few weeks ago?

**Comment by boxabirds** [comment]
I got a chat message from support that fingerprints had been accidentally
disabled and were going again. But I’ve not tested it recently as I’m on
other projects at the moment.

**Comment by artkpv** [comment]
Are current models that support seed only the same as 2 years ago? Namely,  gpt-4-1106-preview and gpt-3.5-turbo-1106. Thanks
