### ISSUE TITLE
OpenAI CIDR Ranges

### ISSUE THREAD

**Issue by Watersoul** [openai/openai-cookbook#896]
Hi,

I have a bunch of sites and some of them has a high load.
So, I use https://openai.com/gptbot.json for identify OpenAi bots and I allow it. 
But some robots use address like 52.230.27.142, that similar to OpenAI but not in CIDR list in https://openai.com/gptbot.json
And thats adderesses has been blocked.
It would be nice, if you could quite more frequently update https://openai.com/gptbot.json table or setup PTR for yours IPs.

**Comment by 0hq** [comment]
Hi! If you're looking for support on GPTBot and robots.txt, the best place to get help is probably the OpenAI help center: [help.openai.com/en](https://help.openai.com/en/).
