### ISSUE TITLE
How to do near-duplicate detection

### ISSUE THREAD

**Issue by localjo** [openai/openai-cookbook#9]
I am looking for examples of how to do near-duplicate detection, as [mentioned in the readme](https://github.com/openai/openai-cookbook#4-compare-text). I'm interested in different examples, but my current use-case is that I have a list of thousands of unique sentences, but I want to detect which of them might have similar semantic meanings. Is there an example of how near-duplicate detection might work?

**Comment by ted-at-openai** [comment]
Is it a public dataset? If so, I can write up an example.

The essence of the idea is to get an embedding for each example. Take the cosine similarity of any two embeddings to compute a similarity score. If the similarity score is over some threshold (say, 0.95) then you can consider them highly similar.

**Comment by ted-at-openai** [comment]
Note that embeddings capture 'topical' similarity more than 'logical' similarity. E.g., `the sky is blue` and `the sky is not blue` will have a high similarity score, as they are both talking about the blueness of the sky.

**Comment by localjo** [comment]
It's not a public dataset, but how many items would you need for an example? I could share 5-10 sample sentences.

I'm wondering if topical similarity would capture topics that aren't explicitly the same. For example, would something like, `my favorite food is chocolate` be considered topically related to `I really like to eat ice cream`?

**Comment by ted-at-openai** [comment]
If I write up an example, it would ideally be with >100 data points and a source of truth to grade the model against.

Those two strings have a cosine similarity of 0.9 using text-similarity-babbage-001.

**Comment by localjo** [comment]
In the end, I was able to find an example that worked for me in the Jupyter notebooks in the Embeddings documentation about "Text search using embeddings": https://beta.openai.com/docs/guides/embeddings/use-cases
