### ISSUE TITLE
[SUPPORT] Still "You exceeded your current quota" after added a new credit balance

### ISSUE THREAD

**Issue by l2aelba** [openai/openai-cookbook#901]
1. My account is out of credit balance.
2. I added a new credit balance.
3. When I try to call the API it  still shows `You exceeded your current quota`

Searched overall, people need to make a new account (why?) or re-create a new API (does not help) or wait for 48 hours (still no luck)

Please fix this ASAP thanks.

**Comment by 0hq** [comment]
Hi! If you're looking for support on our API, please visit the OpenAI help center: https://help.openai.com/en/.
