### ISSUE TITLE
How to use code interpreter to save gpt generated documents such as csv files to local disk

### ISSUE THREAD

**Issue by lihui123456** [openai/openai-cookbook#927]
I have a requirement to generate an excel table according to some known data and save the table to the local disk, I can not save to the local disk, it is always saved in the directory（ /mnt/data/XXX.csv）, I guess it should be the directory of the virtual environment. I have an idea to execute the code generated by the code interpreter locally, but I don't know how to execute it or save the file. Is there any other simpler solution?

llm_config = {
"config_list": config_list,
"assistant_id": assistant_id,
"tools": [
{
"type": "code_interpreter"
}
],
}
gpt_assistant = GPTAssistantAgent(
name="assistant",
instructions="你是一个代码解释器助手，如果需要使用python代码请用代码来解决问题",
llm_config=llm_config)

user_proxy = UserProxyAgent(
name="user_proxy",
is_termination_msg=lambda msg: "TERMINATE" in msg["content"],
code_execution_config={
"work_dir": "coding",
"use_docker": False, # set to True or image name like "python:3" to use docker
},
human_input_mode="NEVER"
)
user_proxy.initiate_chat(
gpt_assistant,
message="随机生成一个csv文件,并保存在本地",
)

If I execute the above code, the path of the generated CSV file is /mnt/data/XXX.csv, as if in a virtual environment, how can I use the file generated by gpt's assistant to locally or download the file generated in the virtual environment? thank you.

**Comment by 0hq** [comment]
Hi! You can read more about the Assistants File API and Code Interpeter here: https://platform.openai.com/docs/assistants/tools/code-interpreter.

You can download a file like so:
`from openai import OpenAI

client = OpenAI()

image_data = client.files.content("file-abc123")
image_data_bytes = image_data.read()

with open("./my-image.png", "wb") as file:
    file.write(image_data_bytes)`
