### ISSUE TITLE
[SUPPORT] New to Contributing

### ISSUE THREAD

**Issue by jstapleton27** [openai/openai-cookbook#928]
I am new to contributing and come from a Pre-Sales Engineering background.  I want to start getting my hands on OpenAI contributions and creating exciting new products/features/prototypes in the OpenAI space.  Any suggestions, guidance, steps, etc. are greatly appreciated.

Cheers!

**Comment by kesku** [comment]
Heya, welcome to the OpenAI community!

For help with OpenAI services it might be best to [check out the cookbook itself](https://cookbook.openai.com/) to get started. It's full of practical examples and use cases that can help you understand the possibilities. The [API documentation](https://platform.openai.com/docs/) is also a great resource to familiarize yourself with the APIs 👍 

For help with contributing on GitHub, [maybe check out this guide](https://github.com/firstcontributions/first-contributions)

Mind if I ask what specifically you're trying to do?
