### ISSUE TITLE
[PROBLEM] Cookbook examples are incompatible with new openai API and libraries

### ISSUE THREAD

**Issue by femibyte** [openai/openai-cookbook#933]
[optional format]

**Identify the file to be fixed**
Open AI cookbook on clustering
https://cookbook.openai.com/examples/clustering#1-find-the-clusters-using-k-means

**Describe the problem**
Many cookbook examples are now obsolete and don't work with the new version of the openai libraries

**Describe a solution**
Update the cookbook examples

**Screenshots**

**Additional context**

**Comment by femibyte** [comment]
<img width="1440" alt="image" src="https://github.com/openai/openai-cookbook/assets/922244/29523b67-309c-4890-9373-5987baf24567">

**Comment by femi-anthony** [comment]
Also the following link : 
[[Code_search.ipynb](https://cookbook.openai.com/examples/code_search)](https://cookbook.openai.com/examples/code_search)

which is referenced in the [embeddings use case page](https://platform.openai.com/docs/guides/embeddings/use-cases)
results in a 404 error.

**Comment by ARajgor** [comment]
Many PR requests have already been created but here is the code if you need it urgently. 

```
from openai import OpenAI
client = OpenAI()

# Reading a review which belong to each group.
rev_per_cluster = 5

for i in range(n_clusters):
    print(f"Cluster {i} Theme:", end=" ")

    reviews = "\n".join(
        df[df.Cluster == i]
        .combined.str.replace("Title: ", "")
        .str.replace("\n\nContent: ", ":  ")
        .sample(rev_per_cluster, random_state=42)
        .values
    )
    response = client.chat.completions.create(
        model="gpt-3.5-turbo",
        messages = [{'role':'user','content':'What do the following customer reviews have in common?\n\nCustomer reviews:\n"""\n{reviews}\n"""\n\nTheme:'}],
        temperature=0,
        max_tokens=64,
        top_p=1,
        frequency_penalty=0,
        presence_penalty=0,
    )
    print(response.choices[0].message.content.replace("\n", ""))

    sample_cluster_rows = df[df.Cluster == i].sample(rev_per_cluster, random_state=42)
    for j in range(rev_per_cluster):
        print(sample_cluster_rows.Score.values[j], end=", ")
        print(sample_cluster_rows.Summary.values[j], end=":   ")
        print(sample_cluster_rows.Text.str[:70].values[j])

    print("-" * 100)

```
