### ISSUE TITLE
Question answering using embeddings error

### ISSUE THREAD

**Issue by stephansturges** [openai/openai-cookbook#96]
I just wanted to point this out:

![image](https://user-images.githubusercontent.com/20320678/215451270-3f1d0454-7f8a-4013-b939-8f976e78597d.png)

It's obviously no big deal, but given the context window of >8000 tokens with davinci-003 it would be a great opportunity to explain that the semantic proximity may not be a perfect metric for prepending context and in this case we solve the issue by prepending multiple articles since the second-closest one is the correct input.

**Comment by simonpfish** [comment]
That's a good thing to point out! We'll consider adding a note on that to the notebook

**Comment by simonpfish** [comment]
Planned
