### ISSUE TITLE
Averages in Embedding_long_inputs.ipynb are weighted by vector length

### ISSUE THREAD

**Issue by JMVaughan** [openai/openai-cookbook#98]
The notebook [Embedding_long_inputs.ipynb](https://github.com/openai/openai-cookbook/tree/main/examples/Embedding_long_inputs.ipynb) performs a weighted average of the embeddings by _length of vector_, however I believe the average should be weighted by _length of chunk_.

**Comment by ted-at-openai** [comment]
Great catch. @filipeabperes, do you want to fix this?

**Comment by filipeabperes** [comment]
❗ on it
